/*
 * Copyright 2018 National Technology & Engineering Solutions of
 * Sandia, LLC (NTESS). Under the terms of Contract DE-NA0003525 with NTESS,
 * the U.S. Government retains certain rights in this software.
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2018 Sandia Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */


#ifndef CLIENTTIMINGCONSTANTS_HH
#define CLIENTTIMINGCONSTANTS_HH

//unsigned short -> max value: 65535
enum CLIENT_TIMING_CONSTANTS : unsigned short {
//10000 - errors
    ERR_ARGC = 10000,
    ERR_DIRMAN = 10001,
    ERR_CREATE_VAR = 10002,
    ERR_CREATE_TYPE = 10003,
    ERR_INSERT_CHUNK = 10004,
    ERR_TYPE_COMPARE = 10005,
    ERR_INSERT_ATTR = 10006,
    ERR_CATALOG_VAR = 10007,
    ERR_PATTERN_1 = 10008,
    ERR_PATTERN_2 = 10009,
    ERR_PATTERN_3 = 10010,
    ERR_PATTERN_4 = 10011,
    ERR_PATTERN_5 = 10012,
    ERR_PATTERN_6 = 10013,

//read pattern errors
    ERR_GET_CHUNK = 10100,
    ERR_GET_ATTR = 10101,
    ERR_VAR_ID_NOT_FOUND = 10102,

//extra testing errors
    ERR_ACTIVATE_VAR = 10200,
    ERR_CATALOG_VAR_EXTRA = 10201,
    ERR_PROCESSING_VAR = 10202,
    ERR_GET_CHUNK_LIST = 10203,
    ERR_ACTIVATE_TYPE = 10204,
    ERR_CATALOG_TYPE = 10205,
    ERR_PROCESSING_TYPE = 10206,
    ERR_GET_ATTR_LIST = 10207,
    ERR_DELETE_VAR = 10208,
    ERR_GET_ATTR_EXTRA= 10209,
    ERR_DELETE_TYPE = 10210,
    ERR_CHUNK_LIST_EMPTY = 10211,


//0-100 testing haress
    PROGRAM_START = 0,
    MPI_INIT_DONE = 1,
    REGISTER_OPS_DONE = 2,
    INIT_VARS_DONE = 3,
    DIRMAN_SETUP_DONE = 4,
    SERVER_SETUP_DONE_INIT_DONE = 5,
    //writing starts
    WRITING_START = 20, 
    CREATE_NEW_VAR_START = 21, 
    VAR_INIT_DONE = 22,
    CREATE_VARS_DONE = 23,
    CREATE_VARS_DONE_START_CREATE_TYPES = 24,
    CREATE_NEW_TYPE_START = 25, 
    TYPE_INIT_DONE = 26,

    CREATE_TYPES_DONE= 27, 
    CHUNK_INIT_DONE = 28,
    INSERT_FOR_NEW_DATASET_START = 29,
    INSERT_FOR_NEW_VAR_START = 30,
    INSERT_ATTRS_START = 31,
    CREATE_NEW_ATTR_START = 32,
    ATTR_INIT_DONE = 33,
    INSERT_ATTRS_DONE = 34,
    INSERT_FOR_NEW_VAR_DONE = 35,
    INSERT_FOR_NEW_DATASET_DONE = 36,
    WRITING_DONE = 37, //new
    //50s - reading
    READING_START = 50,
    READING_SETUP_DONE = 51,
    SERVERS_SETUP_DONE = 52,
    BCAST_CATALOGS_DONE = 53,
    READING_PATTERNS_DONE = 54,
    READING_TYPE_PATTERNS_DONE = 55,
    EXTRA_TESTING_DONE = 56,
    READING_DONE = 57,
    READING_DONE_FOR_ALL_PROCS_START_CLEANUP = 58,
    SERVER_SHUTDOWN_DONE = 59,
    DIRMAN_SHUTDOWN_DONE = 60,

    CLOCK_TIMES_NEW_PROC = 98,
    CLOCK_TIMES_DONE = 99,

//100s - read patterns
    READ_PATTERN_1_START = 100,
    READ_PATTERN_1_VAR_INIT_DONE_START_READING = 101,
    READ_PATTERN_1_START_READING_VAR = 102,
    READ_PATTERN_1_START_READING_FROM_NEW_SERVER = 103,
    READ_PATTERN_1_START_GET_ATTRS = 104,
    READ_PATTERN_1_DONE_GET_ATTRS = 105,
    READ_PATTERN_1_DONE_READING_FROM_SERVER = 106,
    READ_PATTERN_1_DONE_READING_VAR = 107,
    READ_PATTERN_1_DONE_READING = 108,

    READ_PATTERN_2_START = 200,
    READ_PATTERN_2_VAR_INIT_DONE = 201,
    READ_PATTERN_2_BCAST_DONE_START_READING_VAR = 202,
    READ_PATTERN_2_START_READING_FROM_NEW_SERVER = 203,
    READ_PATTERN_2_START_GET_ATTRS = 204,
    READ_PATTERN_2_DONE_GET_ATTRS = 205,
    READ_PATTERN_2_DONE_READING_FROM_SERVER = 206,
    READ_PATTERN_2_DONE_READING = 207,


    READ_PATTERN_3_START = 300,
    READ_PATTERN_3_VAR_INIT_DONE = 301,
    READ_PATTERN_3_BCAST_DONE_START_READING = 302,
    READ_PATTERN_3_START_READING_VAR = 303,
    READ_PATTERN_3_VAR_TO_FIND_INIT_DONE = 304,
    READ_PATTERN_3_START_READING_FROM_NEW_SERVER = 305,
    READ_PATTERN_3_START_GET_ATTRS = 306,
    READ_PATTERN_3_DONE_GET_ATTRS = 307,
    READ_PATTERN_3_DONE_READING_FROM_SERVER = 308,
    READ_PATTERN_3_DONE_READING_VAR = 309,
    READ_PATTERN_3_DONE_READING = 310,


    READ_PATTERN_4_START = 400,
    READ_PATTERN_4_BCAST_DONE_START_READING = 401,
    READ_PATTERN_4_PLANE_TO_FIND_INIT_DONE_START_READING_PLANE = 402,
    READ_PATTERN_4_START_READING_FROM_NEW_SERVER = 403,
    READ_PATTERN_4_START_GET_ATTRS = 404,
    READ_PATTERN_4_DONE_GET_ATTRS = 405,
    READ_PATTERN_4_DONE_READING_FROM_SERVER = 406,
    READ_PATTERN_4_DONE_READING_PLANE = 407,
    READ_PATTERN_4_DONE_READING = 408,

    READ_PATTERN_5_START = 500,
    READ_PATTERN_5_BCAST_DONE = 501,
    READ_PATTERN_5_VAR_INIT_DONE_START_READING = 502,
    READ_PATTERN_5_START_READING_FROM_NEW_SERVER = 503,
    READ_PATTERN_5_START_GET_ATTRS = 504,
    READ_PATTERN_5_DONE_GET_ATTRS = 505,
    READ_PATTERN_5_DONE_READING_FROM_SERVER = 506,
    READ_PATTERN_5_DONE_READING = 507,

    READ_PATTERN_6_START = 600,
    READ_PATTERN_6_BCAST_DONE_START_READING = 601,
    READ_PATTERN_6_PLANE_TO_FIND_INIT_DONE_START_READING_PLANE = 602,
    READ_PATTERN_6_START_READING_FROM_NEW_SERVER = 603,
    READ_PATTERN_6_START_GET_ATTRS = 604,
    READ_PATTERN_6_DONE_GET_ATTRS = 605,
    READ_PATTERN_6_DONE_READING_FROM_SERVER = 606,
    READ_PATTERN_6_DONE_READING_PLANE = 607,
    READ_PATTERN_6_DONE_READING = 608,

//ops
//1000s - var ops, client side
//
    MD_ACTIVATE_VAR_START = 1000,
    // OP_ACTIVATE_VAR_START = 1001,
    OP_ACTIVATE_VAR_SERIALIZE_MSG_FOR_SERVER = 1002,
    // OP_ACTIVATE_VAR_CREATE_MSG_FOR_SERVER = 1003,
    OP_ACTIVATE_VAR_SEND_MSG_TO_SERVER = 1004,
    OP_ACTIVATE_VAR_RETURN_MSG_RECEIVED_FROM_SERVER = 1005,
    // OP_ACTIVATE_VAR_PROMISE_VAL_SET_OP_DONE = 1006,
    MD_ACTIVATE_VAR_DEARCHIVE_RESPONSE_OP_DONE = 1007,
//    
    MD_CATALOG_VAR_START = 1100,
    // OP_CATALOG_VAR_START = 1101,
    OP_CATALOG_VAR_SERIALIZE_MSG_FOR_SERVER = 1102,
    // OP_CATALOG_VAR_CREATE_MSG_FOR_SERVER = 1103,
    OP_CATALOG_VAR_SEND_MSG_TO_SERVER = 1104,
    OP_CATALOG_VAR_RETURN_MSG_RECEIVED_FROM_SERVER = 1105,
    // OP_CATALOG_VAR_PROMISE_VAL_SET_OP_DONE = 1106,
    MD_CATALOG_VAR_DEARCHIVE_RESPONSE_OP_DONE = 1107,

//
    MD_CREATE_VAR_START = 1200,
    // OP_CREATE_VAR_START = 1201,
    OP_CREATE_VAR_SERIALIZE_MSG_FOR_SERVER = 1202,
    // OP_CREATE_VAR_CREATE_MSG_FOR_SERVER = 1203,
    OP_CREATE_VAR_SEND_MSG_TO_SERVER = 1204,
    OP_CREATE_VAR_RETURN_MSG_RECEIVED_FROM_SERVER = 1205,
    // OP_CREATE_VAR_PROMISE_VAL_SET_OP_DONE = 1206,
    MD_CREATE_VAR_DEARCHIVE_RESPONSE_OP_DONE = 1207,


//
    MD_DELETE_VAR_START = 1300,
    // OP_DELETE_VAR_START = 1301,
    OP_DELETE_VAR_SERIALIZE_MSG_FOR_SERVER = 1302,
    // OP_DELETE_VAR_CREATE_MSG_FOR_SERVER = 1303,
    OP_DELETE_VAR_SEND_MSG_TO_SERVER = 1304,
    OP_DELETE_VAR_RETURN_MSG_RECEIVED_FROM_SERVER = 1305,
    // OP_DELETE_VAR_PROMISE_VAL_SET_OP_DONE = 1306,
    MD_DELETE_VAR_DEARCHIVE_RESPONSE_OP_DONE = 1307,


//
    MD_GET_CHUNK_LIST_START = 1400,
    // OP_GET_CHUNK_LIST_START = 1401,
    OP_GET_CHUNK_LIST_SERIALIZE_MSG_FOR_SERVER = 1402,
    // OP_GET_CHUNK_LIST_CREATE_MSG_FOR_SERVER = 1403,
    OP_GET_CHUNK_LIST_SEND_MSG_TO_SERVER = 1404,
    OP_GET_CHUNK_LIST_RETURN_MSG_RECEIVED_FROM_SERVER = 1405,
    // OP_GET_CHUNK_LIST_PROMISE_VAL_SET_OP_DONE = 1406,
    MD_GET_CHUNK_LIST_DEARCHIVE_RESPONSE_OP_DONE = 1407,

//
    MD_GET_CHUNK_START = 1500,
    // OP_GET_CHUNK_START = 1501,
    OP_GET_CHUNK_SERIALIZE_MSG_FOR_SERVER = 1502,
    // OP_GET_CHUNK_CREATE_MSG_FOR_SERVER = 1503,
    OP_GET_CHUNK_SEND_MSG_TO_SERVER = 1504,
    OP_GET_CHUNK_RETURN_MSG_RECEIVED_FROM_SERVER = 1505,
    // OP_GET_CHUNK_PROMISE_VAL_SET_OP_DONE = 1506,
    MD_GET_CHUNK_DEARCHIVE_RESPONSE_OP_DONE = 1507,

//  
    MD_INSERT_CHUNK_START = 1600,
    // OP_INSERT_CHUNK_START = 1601,
    OP_INSERT_CHUNK_SERIALIZE_MSG_FOR_SERVER = 1602,
    // OP_INSERT_CHUNK_CREATE_MSG_FOR_SERVER = 1603,
    OP_INSERT_CHUNK_SEND_MSG_TO_SERVER = 1604,
    OP_INSERT_CHUNK_RETURN_MSG_RECEIVED_FROM_SERVER = 1605,
    // OP_INSERT_CHUNK_PROMISE_VAL_SET_OP_DONE = 1606,
    MD_INSERT_CHUNK_DEARCHIVE_RESPONSE_OP_DONE = 1607,


//
    MD_PROCESSING_VAR_START = 1700,
    // OP_PROCESSING_VAR_START = 1701,
    OP_PROCESSING_VAR_SERIALIZE_MSG_FOR_SERVER = 1702,
    // OP_PROCESSING_VAR_CREATE_MSG_FOR_SERVER = 1703,
    OP_PROCESSING_VAR_SEND_MSG_TO_SERVER = 1704,
    OP_PROCESSING_VAR_RETURN_MSG_RECEIVED_FROM_SERVER = 1705,
    // OP_PROCESSING_VAR_PROMISE_VAL_SET_OP_DONE = 1706, 
    MD_PROCESSING_VAR_DEARCHIVE_RESPONSE_OP_DONE = 1707,




//2000s - type ops
    MD_ACTIVATE_TYPE_START = 2000,
    // OP_ACTIVATE_TYPE_START = 2001,
    OP_ACTIVATE_TYPE_SERIALIZE_MSG_FOR_SERVER = 2002,
    // OP_ACTIVATE_TYPE_CREATE_MSG_FOR_SERVER = 2003,
    OP_ACTIVATE_TYPE_SEND_MSG_TO_SERVER = 2004,
    OP_ACTIVATE_TYPE_RETURN_MSG_RECEIVED_FROM_SERVER = 2005,
    // OP_ACTIVATE_TYPE_PROMISE_VAL_SET_OP_DONE = 2006,
    MD_ACTIVATE_TYPE_DEARCHIVE_RESPONSE_OP_DONE = 2007,
//    
    MD_CATALOG_TYPE_START = 2100,
    // OP_CATALOG_TYPE_START = 2101,
    OP_CATALOG_TYPE_SERIALIZE_MSG_FOR_SERVER = 2102,
    // OP_CATALOG_TYPE_CREATE_MSG_FOR_SERVER = 2103,
    OP_CATALOG_TYPE_SEND_MSG_TO_SERVER = 2104,
    OP_CATALOG_TYPE_RETURN_MSG_RECEIVED_FROM_SERVER = 2105,
    // OP_CATALOG_TYPE_PROMISE_VAL_SET_OP_DONE = 2106,
    MD_CATALOG_TYPE_DEARCHIVE_RESPONSE_OP_DONE = 2107,

//
    MD_CREATE_TYPE_START = 2200,
    // OP_CREATE_TYPE_START = 2201,
    OP_CREATE_TYPE_SERIALIZE_MSG_FOR_SERVER = 2202,
    // OP_CREATE_TYPE_CREATE_MSG_FOR_SERVER = 2203,
    OP_CREATE_TYPE_SEND_MSG_TO_SERVER = 2204,
    OP_CREATE_TYPE_RETURN_MSG_RECEIVED_FROM_SERVER = 2205,
    // OP_CREATE_TYPE_PROMISE_VAL_SET_OP_DONE = 2206,
    MD_CREATE_TYPE_DEARCHIVE_RESPONSE_OP_DONE = 2207,


//
    MD_DELETE_TYPE_START = 2300,
    // OP_DELETE_TYPE_START = 2301,
    OP_DELETE_TYPE_SERIALIZE_MSG_FOR_SERVER = 2302,
    // OP_DELETE_TYPE_CREATE_MSG_FOR_SERVER = 2303,
    OP_DELETE_TYPE_SEND_MSG_TO_SERVER = 2304,
    OP_DELETE_TYPE_RETURN_MSG_RECEIVED_FROM_SERVER = 2305,
    // OP_DELETE_TYPE_PROMISE_VAL_SET_OP_DONE = 2306,
    MD_DELETE_TYPE_DEARCHIVE_RESPONSE_OP_DONE = 2307,


//
    MD_GET_ATTR_LIST_START = 2400,
    // OP_GET_ATTR_LIST_START = 2401,
    OP_GET_ATTR_LIST_SERIALIZE_MSG_FOR_SERVER = 2402,
    // OP_GET_ATTR_LIST_CREATE_MSG_FOR_SERVER = 2403,
    OP_GET_ATTR_LIST_SEND_MSG_TO_SERVER = 2404,
    OP_GET_ATTR_LIST_RETURN_MSG_RECEIVED_FROM_SERVER = 2405,
    // OP_GET_ATTR_LIST_PROMISE_VAL_SET_OP_DONE = 2406,
    MD_GET_ATTR_LIST_DEARCHIVE_RESPONSE_OP_DONE = 2407,

//
    MD_GET_ATTR_START = 2500,
    // OP_GET_ATTR_START = 2501,
    OP_GET_ATTR_SERIALIZE_MSG_FOR_SERVER = 2502,
    // OP_GET_ATTR_CREATE_MSG_FOR_SERVER = 2503,
    OP_GET_ATTR_SEND_MSG_TO_SERVER = 2504,
    OP_GET_ATTR_RETURN_MSG_RECEIVED_FROM_SERVER = 2505,
    // OP_GET_ATTR_PROMISE_VAL_SET_OP_DONE = 2506,
    MD_GET_ATTR_DEARCHIVE_RESPONSE_OP_DONE = 2507,

//  
    MD_INSERT_ATTR_START = 2600,
    // OP_INSERT_ATTR_START = 2601,
    OP_INSERT_ATTR_SERIALIZE_MSG_FOR_SERVER = 2602,
    // OP_INSERT_ATTR_CREATE_MSG_FOR_SERVER = 2603,
    OP_INSERT_ATTR_SEND_MSG_TO_SERVER = 2604,
    OP_INSERT_ATTR_RETURN_MSG_RECEIVED_FROM_SERVER = 2605,
    // OP_INSERT_ATTR_PROMISE_VAL_SET_OP_DONE = 2606,
    MD_INSERT_ATTR_DEARCHIVE_RESPONSE_OP_DONE = 2607,


//
    MD_PROCESSING_TYPE_START = 2700,
    // OP_PROCESSING_TYPE_START = 2701,
    OP_PROCESSING_TYPE_SERIALIZE_MSG_FOR_SERVER = 2702,
    // OP_PROCESSING_TYPE_CREATE_MSG_FOR_SERVER = 2703,
    OP_PROCESSING_TYPE_SEND_MSG_TO_SERVER = 2704,
    OP_PROCESSING_TYPE_RETURN_MSG_RECEIVED_FROM_SERVER = 2705,
    // OP_PROCESSING_TYPE_PROMISE_VAL_SET_OP_DONE = 2706, 
    MD_PROCESSING_TYPE_DEARCHIVE_RESPONSE_OP_DONE = 2707,

 //neither var nor type op
    MD_FULL_SHUTDOWN_START = 3000,
    // OP_FULL_SHUTDOWN_START = 3001,
    // OP_FULL_SHUTDOWN_CREATE_MSG_FOR_SERVER = 3002,
    // OP_FULL_SHUTDOWN_SEND_MSG_TO_SERVER_OP_DONE = 3003,
    MD_FULL_SHUTDOWN_OP_DONE = 3004, 

};

#endif //CLIENTTIMINGCONSTANTS_HH
