/* 
 * Copyright 2018 National Technology & Engineering Solutions of
 * Sandia, LLC (NTESS). Under the terms of Contract DE-NA0003525 with NTESS,
 * the U.S. Government retains certain rights in this software.
 *
 * The MIT License (MIT)
 * 
 * Copyright (c) 2018 Sandia Corporation
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */


#ifndef MDCLIENTTIMINGCONSTANTS_HH
#define MDCLIENTTIMINGCONSTANTS_HH

enum MD_CLIENT_TIMING_CONSTANTS : unsigned short {

//ops
//var ops, note: server side is from **50-**99
//
    MD_ACTIVATE_START = 1000,
    // OP_ACTIVATE_START = 1001,
    OP_ACTIVATE_SERIALIZE_MSG_FOR_SERVER = 1002,
    // OP_ACTIVATE_CREATE_MSG_FOR_SERVER = 1003,
    OP_ACTIVATE_SEND_MSG_TO_SERVER = 1004,
    OP_ACTIVATE_RETURN_MSG_RECEIVED_FROM_SERVER = 1005,
    // OP_ACTIVATE_PROMISE_VAL_SET_OP_DONE = 1006, 
    MD_ACTIVATE_DEARCHIVE_RESPONSE_OP_DONE = 1007,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_START = 1100,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_START = 1101,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SERIALIZE_MSG_FOR_SERVER = 1102,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_CREATE_MSG_FOR_SERVER = 1103,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SEND_MSG_TO_SERVER = 1104,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_RETURN_MSG_RECEIVED_FROM_SERVER = 1105,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_PROMISE_VAL_SET_OP_DONE = 1106, 
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_DEARCHIVE_RESPONSE_OP_DONE = 1107,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_START = 1200,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_START = 1201,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_SERIALIZE_MSG_FOR_SERVER = 1202,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_CREATE_MSG_FOR_SERVER = 1203,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_SEND_MSG_TO_SERVER = 1204,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_RETURN_MSG_RECEIVED_FROM_SERVER = 1205,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_PROMISE_VAL_SET_OP_DONE = 1206, 
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_DEARCHIVE_RESPONSE_OP_DONE = 1207,

//
    MD_CATALOG_RUN_START = 1300,
    // OP_CATALOG_RUN_START = 1301,
    OP_CATALOG_RUN_SERIALIZE_MSG_FOR_SERVER = 1302,
    // OP_CATALOG_RUN_CREATE_MSG_FOR_SERVER = 1303,
    OP_CATALOG_RUN_SEND_MSG_TO_SERVER = 1304,
    OP_CATALOG_RUN_RETURN_MSG_RECEIVED_FROM_SERVER = 1305,
    // OP_CATALOG_RUN_PROMISE_VAL_SET_OP_DONE = 1306, 
    MD_CATALOG_RUN_DEARCHIVE_RESPONSE_OP_DONE = 1307,

//
    MD_CATALOG_TIMESTEP_START = 1400,
    // OP_CATALOG_TIMESTEP_START = 1401,
    OP_CATALOG_TIMESTEP_SERIALIZE_MSG_FOR_SERVER = 1402,
    // OP_CATALOG_TIMESTEP_CREATE_MSG_FOR_SERVER = 1403,
    OP_CATALOG_TIMESTEP_SEND_MSG_TO_SERVER = 1404,
    OP_CATALOG_TIMESTEP_RETURN_MSG_RECEIVED_FROM_SERVER = 1405,
    // OP_CATALOG_TIMESTEP_PROMISE_VAL_SET_OP_DONE = 1406, 
    MD_CATALOG_TIMESTEP_DEARCHIVE_RESPONSE_OP_DONE = 1407,

//
    MD_CATALOG_VAR_START = 1500,
    // OP_CATALOG_VAR_START = 1501,
    OP_CATALOG_VAR_SERIALIZE_MSG_FOR_SERVER = 1502,
    // OP_CATALOG_VAR_CREATE_MSG_FOR_SERVER = 1503,
    OP_CATALOG_VAR_SEND_MSG_TO_SERVER = 1504,
    OP_CATALOG_VAR_RETURN_MSG_RECEIVED_FROM_SERVER = 1505,
    // OP_CATALOG_VAR_PROMISE_VAL_SET_OP_DONE = 1506, 
    MD_CATALOG_VAR_DEARCHIVE_RESPONSE_OP_DONE = 1507,

//
    MD_CREATE_RUN_START = 1600,
    // OP_CREATE_RUN_START = 1601,
    OP_CREATE_RUN_SERIALIZE_MSG_FOR_SERVER = 1602,
    // OP_CREATE_RUN_CREATE_MSG_FOR_SERVER = 1603,
    OP_CREATE_RUN_SEND_MSG_TO_SERVER = 1604,
    OP_CREATE_RUN_RETURN_MSG_RECEIVED_FROM_SERVER = 1605,
    // OP_CREATE_RUN_PROMISE_VAL_SET_OP_DONE = 1606, 
    MD_CREATE_RUN_DEARCHIVE_RESPONSE_OP_DONE = 1607,

//
    MD_CREATE_TIMESTEP_START = 1700,
    // OP_CREATE_TIMESTEP_START = 1701,
    OP_CREATE_TIMESTEP_SERIALIZE_MSG_FOR_SERVER = 1702,
    // OP_CREATE_TIMESTEP_CREATE_MSG_FOR_SERVER = 1703,
    OP_CREATE_TIMESTEP_SEND_MSG_TO_SERVER = 1704,
    OP_CREATE_TIMESTEP_RETURN_MSG_RECEIVED_FROM_SERVER = 1705,
    // OP_CREATE_TIMESTEP_PROMISE_VAL_SET_OP_DONE = 1706, 
    MD_CREATE_TIMESTEP_DEARCHIVE_RESPONSE_OP_DONE = 1707,

//
    MD_CREATE_VAR_START = 1800,
    // OP_CREATE_VAR_START = 1801,
    OP_CREATE_VAR_SERIALIZE_MSG_FOR_SERVER = 1802,
    // OP_CREATE_VAR_CREATE_MSG_FOR_SERVER = 1803,
    OP_CREATE_VAR_SEND_MSG_TO_SERVER = 1804,
    OP_CREATE_VAR_RETURN_MSG_RECEIVED_FROM_SERVER = 1805,
    // OP_CREATE_VAR_PROMISE_VAL_SET_OP_DONE = 1806, 
    MD_CREATE_VAR_DEARCHIVE_RESPONSE_OP_DONE = 1807,

//
    MD_CREATE_VAR_BATCH_START = 1900,
    // OP_CREATE_VAR_BATCH_START = 1901,
    OP_CREATE_VAR_BATCH_SERIALIZE_MSG_FOR_SERVER = 1902,
    // OP_CREATE_VAR_BATCH_CREATE_MSG_FOR_SERVER = 1903,
    OP_CREATE_VAR_BATCH_SEND_MSG_TO_SERVER = 1904,
    OP_CREATE_VAR_BATCH_RETURN_MSG_RECEIVED_FROM_SERVER = 1905,
    // OP_CREATE_VAR_BATCH_PROMISE_VAL_SET_OP_DONE = 1906, 
    MD_CREATE_VAR_BATCH_DEARCHIVE_RESPONSE_OP_DONE = 1907,

//
    MD_DELETE_ALL_VARS_WITH_SUBSTR_START = 2000,
    // OP_DELETE_ALL_VARS_WITH_SUBSTR_START = 2001,
    OP_DELETE_ALL_VARS_WITH_SUBSTR_SERIALIZE_MSG_FOR_SERVER = 2002,
    // OP_DELETE_ALL_VARS_WITH_SUBSTR_CREATE_MSG_FOR_SERVER = 2003,
    OP_DELETE_ALL_VARS_WITH_SUBSTR_SEND_MSG_TO_SERVER = 2004,
    OP_DELETE_ALL_VARS_WITH_SUBSTR_RETURN_MSG_RECEIVED_FROM_SERVER = 2005,
    // OP_DELETE_ALL_VARS_WITH_SUBSTR_PROMISE_VAL_SET_OP_DONE = 2006, 
    MD_DELETE_ALL_VARS_WITH_SUBSTR_DEARCHIVE_RESPONSE_OP_DONE = 2007,

//
    MD_DELETE_RUN_BY_ID_START = 2100,
    // OP_DELETE_RUN_BY_ID_START = 2101,
    OP_DELETE_RUN_BY_ID_SERIALIZE_MSG_FOR_SERVER = 2102,
    // OP_DELETE_RUN_BY_ID_CREATE_MSG_FOR_SERVER = 2103,
    OP_DELETE_RUN_BY_ID_SEND_MSG_TO_SERVER = 2104,
    OP_DELETE_RUN_BY_ID_RETURN_MSG_RECEIVED_FROM_SERVER = 2105,
    // OP_DELETE_RUN_BY_ID_PROMISE_VAL_SET_OP_DONE = 2106, 
    MD_DELETE_RUN_BY_ID_DEARCHIVE_RESPONSE_OP_DONE = 2107,

//
    MD_DELETE_TIMESTEP_BY_ID_START = 2200,
    // OP_DELETE_TIMESTEP_BY_ID_START = 2201,
    OP_DELETE_TIMESTEP_BY_ID_SERIALIZE_MSG_FOR_SERVER = 2202,
    // OP_DELETE_TIMESTEP_BY_ID_CREATE_MSG_FOR_SERVER = 2203,
    OP_DELETE_TIMESTEP_BY_ID_SEND_MSG_TO_SERVER = 2204,
    OP_DELETE_TIMESTEP_BY_ID_RETURN_MSG_RECEIVED_FROM_SERVER = 2205,
    // OP_DELETE_TIMESTEP_BY_ID_PROMISE_VAL_SET_OP_DONE = 2206, 
    MD_DELETE_TIMESTEP_BY_ID_DEARCHIVE_RESPONSE_OP_DONE = 2207,

//
    MD_DELETE_VAR_BY_ID_START = 2300,
    // OP_DELETE_VAR_BY_ID_START = 2301,
    OP_DELETE_VAR_BY_ID_SERIALIZE_MSG_FOR_SERVER = 2302,
    // OP_DELETE_VAR_BY_ID_CREATE_MSG_FOR_SERVER = 2303,
    OP_DELETE_VAR_BY_ID_SEND_MSG_TO_SERVER = 2304,
    OP_DELETE_VAR_BY_ID_RETURN_MSG_RECEIVED_FROM_SERVER = 2305,
    // OP_DELETE_VAR_BY_ID_PROMISE_VAL_SET_OP_DONE = 2306, 
    MD_DELETE_VAR_BY_ID_DEARCHIVE_RESPONSE_OP_DONE = 2307,

//
    MD_DELETE_VAR_BY_NAME_PATH_VER_START = 2400,
    // OP_DELETE_VAR_BY_NAME_PATH_VER_START = 2401,
    OP_DELETE_VAR_BY_NAME_PATH_VER_SERIALIZE_MSG_FOR_SERVER = 2402,
    // OP_DELETE_VAR_BY_NAME_PATH_VER_CREATE_MSG_FOR_SERVER = 2403,
    OP_DELETE_VAR_BY_NAME_PATH_VER_SEND_MSG_TO_SERVER = 2404,
    OP_DELETE_VAR_BY_NAME_PATH_VER_RETURN_MSG_RECEIVED_FROM_SERVER = 2405,
    // OP_DELETE_VAR_BY_NAME_PATH_VER_PROMISE_VAL_SET_OP_DONE = 2406, 
    MD_DELETE_VAR_BY_NAME_PATH_VER_DEARCHIVE_RESPONSE_OP_DONE = 2407,

//
    MD_PROCESSING_START = 2500,
    // OP_PROCESSING_START = 2501,
    OP_PROCESSING_SERIALIZE_MSG_FOR_SERVER = 2502,
    // OP_PROCESSING_CREATE_MSG_FOR_SERVER = 2503,
    OP_PROCESSING_SEND_MSG_TO_SERVER = 2504,
    OP_PROCESSING_RETURN_MSG_RECEIVED_FROM_SERVER = 2505,
    // OP_PROCESSING_PROMISE_VAL_SET_OP_DONE = 2506, 
    MD_PROCESSING_DEARCHIVE_RESPONSE_OP_DONE = 2507,

//
    MD_CATALOG_ALL_RUN_ATTRIBUTES_START = 2600,
    // OP_CATALOG_ALL_RUN_ATTRIBUTES_START = 2601,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_SERIALIZE_MSG_FOR_SERVER = 2602,
    // OP_CATALOG_ALL_RUN_ATTRIBUTES_CREATE_MSG_FOR_SERVER = 2603,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_SEND_MSG_TO_SERVER = 2604,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_RETURN_MSG_RECEIVED_FROM_SERVER = 2605,
    // OP_CATALOG_ALL_RUN_ATTRIBUTES_PROMISE_VAL_SET_OP_DONE = 2606, 
    MD_CATALOG_ALL_RUN_ATTRIBUTES_DEARCHIVE_RESPONSE_OP_DONE = 2607,

//
    MD_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_START = 2700,
    // OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_START = 2701,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_SERIALIZE_MSG_FOR_SERVER = 2702,
    // OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_CREATE_MSG_FOR_SERVER = 2703,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_SEND_MSG_TO_SERVER = 2704,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RETURN_MSG_RECEIVED_FROM_SERVER = 2705,
    // OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_PROMISE_VAL_SET_OP_DONE = 2706, 
    MD_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_DEARCHIVE_RESPONSE_OP_DONE = 2707,

//
    MD_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_START = 2800,
    // OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_START = 2801,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_SERIALIZE_MSG_FOR_SERVER = 2802,
    // OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_CREATE_MSG_FOR_SERVER = 2803,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_SEND_MSG_TO_SERVER = 2804,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_RETURN_MSG_RECEIVED_FROM_SERVER = 2805,
    // OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_PROMISE_VAL_SET_OP_DONE = 2806, 
    MD_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_DEARCHIVE_RESPONSE_OP_DONE = 2807,

//
    MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_START = 2900,
    // OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_START = 2901,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_SERIALIZE_MSG_FOR_SERVER = 2902,
    // OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_CREATE_MSG_FOR_SERVER = 2903,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_SEND_MSG_TO_SERVER = 2904,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_RETURN_MSG_RECEIVED_FROM_SERVER = 2905,
    // OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_PROMISE_VAL_SET_OP_DONE = 2906, 
    MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_DEARCHIVE_RESPONSE_OP_DONE = 2907,

//
    MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_START = 3000,
    // OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_START = 3001,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_SERIALIZE_MSG_FOR_SERVER = 3002,
    // OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_CREATE_MSG_FOR_SERVER = 3003,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_SEND_MSG_TO_SERVER = 3004,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RETURN_MSG_RECEIVED_FROM_SERVER = 3005,
    // OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_PROMISE_VAL_SET_OP_DONE = 3006, 
    MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_DEARCHIVE_RESPONSE_OP_DONE = 3007,

//
    MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_START = 3100,
    // OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_START = 3101,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_SERIALIZE_MSG_FOR_SERVER = 3102,
    // OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_CREATE_MSG_FOR_SERVER = 3103,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_SEND_MSG_TO_SERVER = 3104,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_RETURN_MSG_RECEIVED_FROM_SERVER = 3105,
    // OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_PROMISE_VAL_SET_OP_DONE = 3106, 
    MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_DEARCHIVE_RESPONSE_OP_DONE = 3107,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_START = 3200,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_START = 3201,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SERIALIZE_MSG_FOR_SERVER = 3202,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_CREATE_MSG_FOR_SERVER = 3203,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SEND_MSG_TO_SERVER = 3204,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RETURN_MSG_RECEIVED_FROM_SERVER = 3205,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_PROMISE_VAL_SET_OP_DONE = 3206, 
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DEARCHIVE_RESPONSE_OP_DONE = 3207,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_START = 3300,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_START = 3301,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_SERIALIZE_MSG_FOR_SERVER = 3302,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_CREATE_MSG_FOR_SERVER = 3303,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_SEND_MSG_TO_SERVER = 3304,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RETURN_MSG_RECEIVED_FROM_SERVER = 3305,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_PROMISE_VAL_SET_OP_DONE = 3306, 
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_DEARCHIVE_RESPONSE_OP_DONE = 3307,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_START = 3400,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_START = 3401,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_SERIALIZE_MSG_FOR_SERVER = 3402,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_CREATE_MSG_FOR_SERVER = 3403,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_SEND_MSG_TO_SERVER = 3404,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_RETURN_MSG_RECEIVED_FROM_SERVER = 3405,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_PROMISE_VAL_SET_OP_DONE = 3406, 
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_DEARCHIVE_RESPONSE_OP_DONE = 3407,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_START = 3500,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_START = 3501,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_SERIALIZE_MSG_FOR_SERVER = 3502,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_CREATE_MSG_FOR_SERVER = 3503,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_SEND_MSG_TO_SERVER = 3504,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_RETURN_MSG_RECEIVED_FROM_SERVER = 3505,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_PROMISE_VAL_SET_OP_DONE = 3506, 
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_DEARCHIVE_RESPONSE_OP_DONE = 3507,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_START = 3600,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_START = 3601,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_SERIALIZE_MSG_FOR_SERVER = 3602,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_CREATE_MSG_FOR_SERVER = 3603,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_SEND_MSG_TO_SERVER = 3604,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RETURN_MSG_RECEIVED_FROM_SERVER = 3605,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_PROMISE_VAL_SET_OP_DONE = 3606, 
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DEARCHIVE_RESPONSE_OP_DONE = 3607,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_START = 3700,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_START = 3701,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_SERIALIZE_MSG_FOR_SERVER = 3702,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_CREATE_MSG_FOR_SERVER = 3703,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_SEND_MSG_TO_SERVER = 3704,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RETURN_MSG_RECEIVED_FROM_SERVER = 3705,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_PROMISE_VAL_SET_OP_DONE = 3706, 
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_DEARCHIVE_RESPONSE_OP_DONE = 3707,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_START = 3800,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_START = 3801,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_SERIALIZE_MSG_FOR_SERVER = 3802,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_CREATE_MSG_FOR_SERVER = 3803,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_SEND_MSG_TO_SERVER = 3804,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_RETURN_MSG_RECEIVED_FROM_SERVER = 3805,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_PROMISE_VAL_SET_OP_DONE = 3806, 
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_DEARCHIVE_RESPONSE_OP_DONE = 3807,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_START = 3900,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_START = 3901,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_SERIALIZE_MSG_FOR_SERVER = 3902,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_CREATE_MSG_FOR_SERVER = 3903,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_SEND_MSG_TO_SERVER = 3904,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_RETURN_MSG_RECEIVED_FROM_SERVER = 3905,
    // OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_PROMISE_VAL_SET_OP_DONE = 3906, 
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_DEARCHIVE_RESPONSE_OP_DONE = 3907,

//
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_START = 4000,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_START = 4001,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_SERIALIZE_MSG_FOR_SERVER = 4002,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_CREATE_MSG_FOR_SERVER = 4003,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_SEND_MSG_TO_SERVER = 4004,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_RETURN_MSG_RECEIVED_FROM_SERVER = 4005,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_PROMISE_VAL_SET_OP_DONE = 4006, 
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_DEARCHIVE_RESPONSE_OP_DONE = 4007,

//
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_START = 4100,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_START = 4101,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_SERIALIZE_MSG_FOR_SERVER = 4102,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_CREATE_MSG_FOR_SERVER = 4103,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_SEND_MSG_TO_SERVER = 4104,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_RETURN_MSG_RECEIVED_FROM_SERVER = 4105,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_PROMISE_VAL_SET_OP_DONE = 4106, 
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_DEARCHIVE_RESPONSE_OP_DONE = 4107,

//
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_START = 4200,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_START = 4201,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_SERIALIZE_MSG_FOR_SERVER = 4202,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_CREATE_MSG_FOR_SERVER = 4203,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_SEND_MSG_TO_SERVER = 4204,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_RETURN_MSG_RECEIVED_FROM_SERVER = 4205,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_PROMISE_VAL_SET_OP_DONE = 4206, 
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_DEARCHIVE_RESPONSE_OP_DONE = 4207,

//
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_START = 4300,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_START = 4301,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_SERIALIZE_MSG_FOR_SERVER = 4302,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_CREATE_MSG_FOR_SERVER = 4303,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_SEND_MSG_TO_SERVER = 4304,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_RETURN_MSG_RECEIVED_FROM_SERVER = 4305,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_PROMISE_VAL_SET_OP_DONE = 4306, 
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_DEARCHIVE_RESPONSE_OP_DONE = 4307,

//
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_START = 4400,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_START = 4401,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_SERIALIZE_MSG_FOR_SERVER = 4402,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_CREATE_MSG_FOR_SERVER = 4403,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_SEND_MSG_TO_SERVER = 4404,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_RETURN_MSG_RECEIVED_FROM_SERVER = 4405,
    // OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_PROMISE_VAL_SET_OP_DONE = 4406, 
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_DEARCHIVE_RESPONSE_OP_DONE = 4407,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_START = 4500,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_START = 4501,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_SERIALIZE_MSG_FOR_SERVER = 4502,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_CREATE_MSG_FOR_SERVER = 4503,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_SEND_MSG_TO_SERVER = 4504,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_RETURN_MSG_RECEIVED_FROM_SERVER = 4505,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_PROMISE_VAL_SET_OP_DONE = 4506, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_DEARCHIVE_RESPONSE_OP_DONE = 4507,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_START = 4600,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_START = 4601,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_SERIALIZE_MSG_FOR_SERVER = 4602,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_CREATE_MSG_FOR_SERVER = 4603,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_SEND_MSG_TO_SERVER = 4604,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_RETURN_MSG_RECEIVED_FROM_SERVER = 4605,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_PROMISE_VAL_SET_OP_DONE = 4606, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_DEARCHIVE_RESPONSE_OP_DONE = 4607,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_START = 4700,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_START = 4701,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_SERIALIZE_MSG_FOR_SERVER = 4702,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_CREATE_MSG_FOR_SERVER = 4703,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_SEND_MSG_TO_SERVER = 4704,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_RETURN_MSG_RECEIVED_FROM_SERVER = 4705,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_PROMISE_VAL_SET_OP_DONE = 4706, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_DEARCHIVE_RESPONSE_OP_DONE = 4707,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_START = 4800,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_START = 4801,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_SERIALIZE_MSG_FOR_SERVER = 4802,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_CREATE_MSG_FOR_SERVER = 4803,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_SEND_MSG_TO_SERVER = 4804,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_RETURN_MSG_RECEIVED_FROM_SERVER = 4805,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_PROMISE_VAL_SET_OP_DONE = 4806, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_DEARCHIVE_RESPONSE_OP_DONE = 4807,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_START = 4900,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_START = 4901,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_SERIALIZE_MSG_FOR_SERVER = 4902,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_CREATE_MSG_FOR_SERVER = 4903,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_SEND_MSG_TO_SERVER = 4904,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_RETURN_MSG_RECEIVED_FROM_SERVER = 4905,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_PROMISE_VAL_SET_OP_DONE = 4906, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_DEARCHIVE_RESPONSE_OP_DONE = 4907,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_START = 5000,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_START = 5001,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_SERIALIZE_MSG_FOR_SERVER = 5002,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_CREATE_MSG_FOR_SERVER = 5003,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_SEND_MSG_TO_SERVER = 5004,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_RETURN_MSG_RECEIVED_FROM_SERVER = 5005,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_PROMISE_VAL_SET_OP_DONE = 5006, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_DEARCHIVE_RESPONSE_OP_DONE = 5007,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_START = 5100,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_START = 5101,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_SERIALIZE_MSG_FOR_SERVER = 5102,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_CREATE_MSG_FOR_SERVER = 5103,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_SEND_MSG_TO_SERVER = 5104,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_RETURN_MSG_RECEIVED_FROM_SERVER = 5105,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_PROMISE_VAL_SET_OP_DONE = 5106, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_DEARCHIVE_RESPONSE_OP_DONE = 5107,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_START = 5200,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_START = 5201,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_SERIALIZE_MSG_FOR_SERVER = 5202,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_CREATE_MSG_FOR_SERVER = 5203,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_SEND_MSG_TO_SERVER = 5204,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_RETURN_MSG_RECEIVED_FROM_SERVER = 5205,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_PROMISE_VAL_SET_OP_DONE = 5206, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_DEARCHIVE_RESPONSE_OP_DONE = 5207,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_START = 5300,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_START = 5301,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_SERIALIZE_MSG_FOR_SERVER = 5302,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_CREATE_MSG_FOR_SERVER = 5303,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_SEND_MSG_TO_SERVER = 5304,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_RETURN_MSG_RECEIVED_FROM_SERVER = 5305,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_PROMISE_VAL_SET_OP_DONE = 5306, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_DEARCHIVE_RESPONSE_OP_DONE = 5307,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_START = 5400,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_START = 5401,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_SERIALIZE_MSG_FOR_SERVER = 5402,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_CREATE_MSG_FOR_SERVER = 5403,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_SEND_MSG_TO_SERVER = 5404,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_RETURN_MSG_RECEIVED_FROM_SERVER = 5405,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_PROMISE_VAL_SET_OP_DONE = 5406, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_DEARCHIVE_RESPONSE_OP_DONE = 5407,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_START = 5500,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_START = 5501,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_SERIALIZE_MSG_FOR_SERVER = 5502,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_CREATE_MSG_FOR_SERVER = 5503,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_SEND_MSG_TO_SERVER = 5504,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_RETURN_MSG_RECEIVED_FROM_SERVER = 5505,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_PROMISE_VAL_SET_OP_DONE = 5506, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_DEARCHIVE_RESPONSE_OP_DONE = 5507,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_START = 5600,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_START = 5601,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_SERIALIZE_MSG_FOR_SERVER = 5602,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_CREATE_MSG_FOR_SERVER = 5603,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_SEND_MSG_TO_SERVER = 5604,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_RETURN_MSG_RECEIVED_FROM_SERVER = 5605,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_PROMISE_VAL_SET_OP_DONE = 5606, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_DEARCHIVE_RESPONSE_OP_DONE = 5607,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_START = 5700,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_START = 5701,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_SERIALIZE_MSG_FOR_SERVER = 5702,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_CREATE_MSG_FOR_SERVER = 5703,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_SEND_MSG_TO_SERVER = 5704,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RETURN_MSG_RECEIVED_FROM_SERVER = 5705,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_PROMISE_VAL_SET_OP_DONE = 5706, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DEARCHIVE_RESPONSE_OP_DONE = 5707,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_START = 5800,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_START = 5801,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_SERIALIZE_MSG_FOR_SERVER = 5802,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_CREATE_MSG_FOR_SERVER = 5803,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_SEND_MSG_TO_SERVER = 5804,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RETURN_MSG_RECEIVED_FROM_SERVER = 5805,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_PROMISE_VAL_SET_OP_DONE = 5806, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_DEARCHIVE_RESPONSE_OP_DONE = 5807,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_START = 5900,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_START = 5901,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_SERIALIZE_MSG_FOR_SERVER = 5902,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_CREATE_MSG_FOR_SERVER = 5903,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_SEND_MSG_TO_SERVER = 5904,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_RETURN_MSG_RECEIVED_FROM_SERVER = 5905,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_PROMISE_VAL_SET_OP_DONE = 5906, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_DEARCHIVE_RESPONSE_OP_DONE = 5907,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_START = 6000,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_START = 6001,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_SERIALIZE_MSG_FOR_SERVER = 6002,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_CREATE_MSG_FOR_SERVER = 6003,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_SEND_MSG_TO_SERVER = 6004,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_RETURN_MSG_RECEIVED_FROM_SERVER = 6005,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_PROMISE_VAL_SET_OP_DONE = 6006, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_DEARCHIVE_RESPONSE_OP_DONE = 6007,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_START = 6100,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_START = 6101,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_SERIALIZE_MSG_FOR_SERVER = 6102,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_CREATE_MSG_FOR_SERVER = 6103,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_SEND_MSG_TO_SERVER = 6104,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_RETURN_MSG_RECEIVED_FROM_SERVER = 6105,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_PROMISE_VAL_SET_OP_DONE = 6106, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_DEARCHIVE_RESPONSE_OP_DONE = 6107,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_START = 6200,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_START = 6201,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_SERIALIZE_MSG_FOR_SERVER = 6202,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_CREATE_MSG_FOR_SERVER = 6203,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_SEND_MSG_TO_SERVER = 6204,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_RETURN_MSG_RECEIVED_FROM_SERVER = 6205,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_PROMISE_VAL_SET_OP_DONE = 6206, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_DEARCHIVE_RESPONSE_OP_DONE = 6207,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_START = 6300,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_START = 6301,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_SERIALIZE_MSG_FOR_SERVER = 6302,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_CREATE_MSG_FOR_SERVER = 6303,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_SEND_MSG_TO_SERVER = 6304,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_RETURN_MSG_RECEIVED_FROM_SERVER = 6305,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_PROMISE_VAL_SET_OP_DONE = 6306, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_DEARCHIVE_RESPONSE_OP_DONE = 6307,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_START = 6400,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_START = 6401,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_SERIALIZE_MSG_FOR_SERVER = 6402,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_CREATE_MSG_FOR_SERVER = 6403,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_SEND_MSG_TO_SERVER = 6404,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_RETURN_MSG_RECEIVED_FROM_SERVER = 6405,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_PROMISE_VAL_SET_OP_DONE = 6406, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_DEARCHIVE_RESPONSE_OP_DONE = 6407,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_START = 6500,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_START = 6501,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_SERIALIZE_MSG_FOR_SERVER = 6502,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_CREATE_MSG_FOR_SERVER = 6503,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_SEND_MSG_TO_SERVER = 6504,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_RETURN_MSG_RECEIVED_FROM_SERVER = 6505,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_PROMISE_VAL_SET_OP_DONE = 6506, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DEARCHIVE_RESPONSE_OP_DONE = 6507,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_START = 6600,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_START = 6601,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_SERIALIZE_MSG_FOR_SERVER = 6602,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_CREATE_MSG_FOR_SERVER = 6603,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_SEND_MSG_TO_SERVER = 6604,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_RETURN_MSG_RECEIVED_FROM_SERVER = 6605,
    // OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_PROMISE_VAL_SET_OP_DONE = 6606, 
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_DEARCHIVE_RESPONSE_OP_DONE = 6607,

//
    MD_CATALOG_TYPE_START = 6700,
    // OP_CATALOG_TYPE_START = 6701,
    OP_CATALOG_TYPE_SERIALIZE_MSG_FOR_SERVER = 6702,
    // OP_CATALOG_TYPE_CREATE_MSG_FOR_SERVER = 6703,
    OP_CATALOG_TYPE_SEND_MSG_TO_SERVER = 6704,
    OP_CATALOG_TYPE_RETURN_MSG_RECEIVED_FROM_SERVER = 6705,
    // OP_CATALOG_TYPE_PROMISE_VAL_SET_OP_DONE = 6706, 
    MD_CATALOG_TYPE_DEARCHIVE_RESPONSE_OP_DONE = 6707,

//
    MD_CREATE_TYPE_START = 6800,
    // OP_CREATE_TYPE_START = 6801,
    OP_CREATE_TYPE_SERIALIZE_MSG_FOR_SERVER = 6802,
    // OP_CREATE_TYPE_CREATE_MSG_FOR_SERVER = 6803,
    OP_CREATE_TYPE_SEND_MSG_TO_SERVER = 6804,
    OP_CREATE_TYPE_RETURN_MSG_RECEIVED_FROM_SERVER = 6805,
    // OP_CREATE_TYPE_PROMISE_VAL_SET_OP_DONE = 6806, 
    MD_CREATE_TYPE_DEARCHIVE_RESPONSE_OP_DONE = 6807,

//
    MD_CREATE_TYPE_BATCH_START = 6900,
    // OP_CREATE_TYPE_BATCH_START = 6901,
    OP_CREATE_TYPE_BATCH_SERIALIZE_MSG_FOR_SERVER = 6902,
    // OP_CREATE_TYPE_BATCH_CREATE_MSG_FOR_SERVER = 6903,
    OP_CREATE_TYPE_BATCH_SEND_MSG_TO_SERVER = 6904,
    OP_CREATE_TYPE_BATCH_RETURN_MSG_RECEIVED_FROM_SERVER = 6905,
    // OP_CREATE_TYPE_BATCH_PROMISE_VAL_SET_OP_DONE = 6906, 
    MD_CREATE_TYPE_BATCH_DEARCHIVE_RESPONSE_OP_DONE = 6907,

//
    MD_DELETE_TYPE_BY_ID_START = 7000,
    // OP_DELETE_TYPE_BY_ID_START = 7001,
    OP_DELETE_TYPE_BY_ID_SERIALIZE_MSG_FOR_SERVER = 7002,
    // OP_DELETE_TYPE_BY_ID_CREATE_MSG_FOR_SERVER = 7003,
    OP_DELETE_TYPE_BY_ID_SEND_MSG_TO_SERVER = 7004,
    OP_DELETE_TYPE_BY_ID_RETURN_MSG_RECEIVED_FROM_SERVER = 7005,
    // OP_DELETE_TYPE_BY_ID_PROMISE_VAL_SET_OP_DONE = 7006, 
    MD_DELETE_TYPE_BY_ID_DEARCHIVE_RESPONSE_OP_DONE = 7007,

//
    MD_DELETE_TYPE_BY_NAME_VER_START = 7100,
    // OP_DELETE_TYPE_BY_NAME_VER_START = 7101,
    OP_DELETE_TYPE_BY_NAME_VER_SERIALIZE_MSG_FOR_SERVER = 7102,
    // OP_DELETE_TYPE_BY_NAME_VER_CREATE_MSG_FOR_SERVER = 7103,
    OP_DELETE_TYPE_BY_NAME_VER_SEND_MSG_TO_SERVER = 7104,
    OP_DELETE_TYPE_BY_NAME_VER_RETURN_MSG_RECEIVED_FROM_SERVER = 7105,
    // OP_DELETE_TYPE_BY_NAME_VER_PROMISE_VAL_SET_OP_DONE = 7106, 
    MD_DELETE_TYPE_BY_NAME_VER_DEARCHIVE_RESPONSE_OP_DONE = 7107,

//
    MD_INSERT_RUN_ATTRIBUTE_START = 7200,
    // OP_INSERT_RUN_ATTRIBUTE_START = 7201,
    OP_INSERT_RUN_ATTRIBUTE_SERIALIZE_MSG_FOR_SERVER = 7202,
    // OP_INSERT_RUN_ATTRIBUTE_CREATE_MSG_FOR_SERVER = 7203,
    OP_INSERT_RUN_ATTRIBUTE_SEND_MSG_TO_SERVER = 7204,
    OP_INSERT_RUN_ATTRIBUTE_RETURN_MSG_RECEIVED_FROM_SERVER = 7205,
    // OP_INSERT_RUN_ATTRIBUTE_PROMISE_VAL_SET_OP_DONE = 7206, 
    MD_INSERT_RUN_ATTRIBUTE_DEARCHIVE_RESPONSE_OP_DONE = 7207,

//
    MD_INSERT_RUN_ATTRIBUTE_BATCH_START = 7300,
    // OP_INSERT_RUN_ATTRIBUTE_BATCH_START = 7301,
    OP_INSERT_RUN_ATTRIBUTE_BATCH_SERIALIZE_MSG_FOR_SERVER = 7302,
    // OP_INSERT_RUN_ATTRIBUTE_BATCH_CREATE_MSG_FOR_SERVER = 7303,
    OP_INSERT_RUN_ATTRIBUTE_BATCH_SEND_MSG_TO_SERVER = 7304,
    OP_INSERT_RUN_ATTRIBUTE_BATCH_RETURN_MSG_RECEIVED_FROM_SERVER = 7305,
    // OP_INSERT_RUN_ATTRIBUTE_BATCH_PROMISE_VAL_SET_OP_DONE = 7306, 
    MD_INSERT_RUN_ATTRIBUTE_BATCH_DEARCHIVE_RESPONSE_OP_DONE = 7307,

//
    MD_INSERT_TIMESTEP_ATTRIBUTE_START = 7400,
    // OP_INSERT_TIMESTEP_ATTRIBUTE_START = 7401,
    OP_INSERT_TIMESTEP_ATTRIBUTE_SERIALIZE_MSG_FOR_SERVER = 7402,
    // OP_INSERT_TIMESTEP_ATTRIBUTE_CREATE_MSG_FOR_SERVER = 7403,
    OP_INSERT_TIMESTEP_ATTRIBUTE_SEND_MSG_TO_SERVER = 7404,
    OP_INSERT_TIMESTEP_ATTRIBUTE_RETURN_MSG_RECEIVED_FROM_SERVER = 7405,
    // OP_INSERT_TIMESTEP_ATTRIBUTE_PROMISE_VAL_SET_OP_DONE = 7406, 
    MD_INSERT_TIMESTEP_ATTRIBUTE_DEARCHIVE_RESPONSE_OP_DONE = 7407,

//
    MD_INSERT_TIMESTEP_ATTRIBUTE_BATCH_START = 7500,
    // OP_INSERT_TIMESTEP_ATTRIBUTE_BATCH_START = 7501,
    OP_INSERT_TIMESTEP_ATTRIBUTE_BATCH_SERIALIZE_MSG_FOR_SERVER = 7502,
    // OP_INSERT_TIMESTEP_ATTRIBUTE_BATCH_CREATE_MSG_FOR_SERVER = 7503,
    OP_INSERT_TIMESTEP_ATTRIBUTE_BATCH_SEND_MSG_TO_SERVER = 7504,
    OP_INSERT_TIMESTEP_ATTRIBUTE_BATCH_RETURN_MSG_RECEIVED_FROM_SERVER = 7505,
    // OP_INSERT_TIMESTEP_ATTRIBUTE_BATCH_PROMISE_VAL_SET_OP_DONE = 7506, 
    MD_INSERT_TIMESTEP_ATTRIBUTE_BATCH_DEARCHIVE_RESPONSE_OP_DONE = 7507,

//
    MD_INSERT_VAR_ATTRIBUTE_BY_DIMS_START = 7600,
    // OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_START = 7601,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_SERIALIZE_MSG_FOR_SERVER = 7602,
    // OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_CREATE_MSG_FOR_SERVER = 7603,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_SEND_MSG_TO_SERVER = 7604,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_RETURN_MSG_RECEIVED_FROM_SERVER = 7605,
    // OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_PROMISE_VAL_SET_OP_DONE = 7606, 
    MD_INSERT_VAR_ATTRIBUTE_BY_DIMS_DEARCHIVE_RESPONSE_OP_DONE = 7607,

//
    MD_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_START = 7700,
    // OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_START = 7701,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_SERIALIZE_MSG_FOR_SERVER = 7702,
    // OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_CREATE_MSG_FOR_SERVER = 7703,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_SEND_MSG_TO_SERVER = 7704,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_RETURN_MSG_RECEIVED_FROM_SERVER = 7705,
    // OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_PROMISE_VAL_SET_OP_DONE = 7706, 
    MD_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_DEARCHIVE_RESPONSE_OP_DONE = 7707,

//
    MD_FULL_SHUTDOWN_START = 7800,
    // OP_FULL_SHUTDOWN_START = 7801,
    // OP_FULL_SHUTDOWN_CREATE_MSG_FOR_SERVER = 7803,
    // OP_FULL_SHUTDOWN_SEND_MSG_TO_SERVER_OP_DONE = 7804,
    MD_FULL_SHUTDOWN_OP_DONE = 7807,

};

#endif //CLIENTTIMINGCONSTANTS_HH

