



#ifndef MDCLIENTTIMINGCONSTANTS_HH
#define MDCLIENTTIMINGCONSTANTS_HH

enum MD_CLIENT_TIMING_CONSTANTS : unsigned short {


    DB_LOAD_START = 993,
    DB_LOAD_DONE = 994,
    DB_LOAD_MULTI_START = 995,
   	DB_LOAD_MULTI_DONE = 996,
   	DB_OUTPUT_START = 997,
    DB_OUTPUT_DONE = 998,

    DB_SIZES = 999,

	ERR_DB_SETUP = 10099,


//ops
//var ops, note: server side is from **50-**99
//
    MD_ACTIVATE_START = 1000,
    MD_ACTIVATE_DONE = 1007,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_START = 1100,
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_DONE = 1107,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_START = 1200,
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_DONE = 1207,

//
    MD_CATALOG_RUN_START = 1300,
    MD_CATALOG_RUN_DONE = 1307,

//
    MD_CATALOG_TIMESTEP_START = 1400,
    MD_CATALOG_TIMESTEP_DONE = 1407,

//
    MD_CATALOG_VAR_START = 1500,
    MD_CATALOG_VAR_DONE = 1507,

//
    MD_CREATE_RUN_START = 1600,
    MD_CREATE_RUN_DONE = 1607,

//
    MD_CREATE_TIMESTEP_START = 1700,
    MD_CREATE_TIMESTEP_DONE = 1707,

//
    MD_CREATE_VAR_START = 1800,
    MD_CREATE_VAR_DONE = 1807,

//
    MD_CREATE_VAR_BATCH_START = 1900,
    MD_CREATE_VAR_BATCH_DONE = 1907,

//
    MD_DELETE_ALL_VARS_WITH_SUBSTR_START = 2000,
    MD_DELETE_ALL_VARS_WITH_SUBSTR_DONE = 2007,

//
    MD_DELETE_RUN_BY_ID_START = 2100,
    MD_DELETE_RUN_BY_ID_DONE = 2107,

//
    MD_DELETE_TIMESTEP_BY_ID_START = 2200,
    MD_DELETE_TIMESTEP_BY_ID_DONE = 2207,

//
    MD_DELETE_VAR_BY_ID_START = 2300,
    MD_DELETE_VAR_BY_ID_DONE = 2307,

//
    MD_DELETE_VAR_BY_NAME_PATH_VER_START = 2400,
    MD_DELETE_VAR_BY_NAME_PATH_VER_DONE = 2407,

//
    MD_PROCESSING_START = 2500,
    MD_PROCESSING_DONE = 2507,

//
    MD_CATALOG_ALL_RUN_ATTRIBUTES_START = 2600,
    MD_CATALOG_ALL_RUN_ATTRIBUTES_DONE = 2607,

//
    MD_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_START = 2700,
    MD_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_DONE = 2707,

//
    MD_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_START = 2800,
    MD_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_DONE = 2807,

//
    MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_START = 2900,
    MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_DONE = 2907,

//
    MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_START = 3000,
    MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_DONE = 3007,

//
    MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_START = 3100,
    MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_DONE = 3107,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_START = 3200,
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DONE = 3207,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_START = 3300,
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_DONE = 3307,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_START = 3400,
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_DONE = 3407,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_START = 3500,
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_DONE = 3507,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_START = 3600,
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DONE = 3607,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_START = 3700,
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_DONE = 3707,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_START = 3800,
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_DONE = 3807,

//
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_START = 3900,
    MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_DONE = 3907,

//
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_START = 4000,
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_DONE = 4007,

//
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_START = 4100,
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_DONE = 4107,

//
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_START = 4200,
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_DONE = 4207,

//
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_START = 4300,
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_DONE = 4307,

//
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_START = 4400,
    MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_DONE = 4407,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_START = 4500,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_DONE = 4507,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_START = 4600,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_DONE = 4607,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_START = 4700,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_DONE = 4707,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_START = 4800,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_DONE = 4807,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_START = 4900,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_DONE = 4907,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_START = 5000,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_DONE = 5007,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_START = 5100,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_DONE = 5107,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_START = 5200,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_DONE = 5207,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_START = 5300,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_DONE = 5307,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_START = 5400,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_DONE = 5407,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_START = 5500,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_DONE = 5507,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_START = 5600,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_DONE = 5607,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_START = 5700,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DONE = 5707,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_START = 5800,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_DONE = 5807,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_START = 5900,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_DONE = 5907,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_START = 6000,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_DONE = 6007,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_START = 6100,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_DONE = 6107,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_START = 6200,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_DONE = 6207,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_START = 6300,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_DONE = 6307,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_START = 6400,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_DONE = 6407,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_START = 6500,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DONE = 6507,

//
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_START = 6600,
    MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_DONE = 6607,

//
    MD_CATALOG_TYPE_START = 6700,
    MD_CATALOG_TYPE_DONE = 6707,

//
    MD_CREATE_TYPE_START = 6800,
    MD_CREATE_TYPE_DONE = 6807,

//
    MD_CREATE_TYPE_BATCH_START = 6900,
    MD_CREATE_TYPE_BATCH_DONE = 6907,

//
    MD_DELETE_TYPE_BY_ID_START = 7000,
    MD_DELETE_TYPE_BY_ID_DONE = 7007,

//
    MD_DELETE_TYPE_BY_NAME_VER_START = 7100,
    MD_DELETE_TYPE_BY_NAME_VER_DONE = 7107,

//
    MD_INSERT_RUN_ATTRIBUTE_START = 7200,
    MD_INSERT_RUN_ATTRIBUTE_DONE = 7207,

//
    MD_INSERT_RUN_ATTRIBUTE_BATCH_START = 7300,
    MD_INSERT_RUN_ATTRIBUTE_BATCH_DONE = 7307,

//
    MD_INSERT_TIMESTEP_ATTRIBUTE_START = 7400,
    MD_INSERT_TIMESTEP_ATTRIBUTE_DONE = 7407,

//
    MD_INSERT_TIMESTEP_ATTRIBUTE_BATCH_START = 7500,
    MD_INSERT_TIMESTEP_ATTRIBUTE_BATCH_DONE = 7507,

//
    MD_INSERT_VAR_ATTRIBUTE_BY_DIMS_START = 7600,
    MD_INSERT_VAR_ATTRIBUTE_BY_DIMS_DONE = 7607,

//
    MD_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_START = 7700,
    MD_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_DONE = 7707,

//
    MD_FULL_SHUTDOWN_START = 7800,

};

#endif //CLIENTTIMINGCONSTANTS_HH

