

#ifndef COMMONTIMINGCONSTANTSCLASSPROJ_HH
#define COMMONTIMINGCONSTANTSCLASSPROJ_HH
enum COMMON_TIMING_CONSTANTS : unsigned short {
	ERR_ARGC = 10000,
    ERR_DIRMAN = 10001,

   	PROGRAM_START = 0,
    MPI_INIT_DONE = 1,
};
#endif //COMMONTIMINGCONSTANTSCLASSPROJ_HH


#ifndef CLIENTTIMINGCONSTANTSWRITECLASSPROJ_HH
#define CLIENTTIMINGCONSTANTSWRITECLASSPROJ_HH
//unsigned short -> max value: 65535
enum CLIENT_TIMING_CONSTANTS_WRITE : unsigned short {
    // ERR_ARGC = 10000,
    // ERR_DIRMAN = 10001,
    ERR_CREATE_TIMESTEP = 10002,
    ERR_CREATE_RUN = 10003,
    ERR_ACTIVATE_RUN = 10004,
    ERR_CREATE_TYPE = 10005,

    ERR_CREATE_TYPE_BATCH = 10006,
    ERR_ACTIVATE_TYPE = 10007,
    ERR_CREATE_VAR = 10008,
    ERR_CREATE_VAR_BATCH = 10009,
    ERR_TYPE_COMPARE = 10010,
    ERR_INSERT_VAR_ATTR = 10011,

    ERR_INSERT_VAR_ATTR_BATCH = 10012,
    ERR_INSERT_TIMESTEP_ATTR_BATCH = 10013,
    ERR_INSERT_TIMESTEP_ATTR = 10014,
    ERR_ACTIVATE_TIMESTEP = 10015,
    ERR_ACTIVATE_VAR = 10016,
    ERR_ACTIVATE_VAR_ATTR = 10017,

    ERR_ACTIVATE_TIMESTEP_ATTR = 10018,
    ERR_INSERT_RUN_ATTR_BATCH = 10019,
    ERR_INSERT_RUN_ATTR = 10020,
    ERR_ACTIVATE_RUN_ATTR = 10021,

    // PROGRAM_START = 0,
    // MPI_INIT_DONE = 1,
    METADATA_CLIENT_INIT_DONE = 2,
    INIT_VARS_DONE = 3,
    DIRMAN_SETUP_DONE = 4,
    SERVER_SETUP_DONE_INIT_DONE = 5,

    WRITING_START = 6,
    CREATE_TIMESTEPS_START = 7,
    CREATE_NEW_TIMESTEP_START = 8,
    CREATE_VARS_AND_ATTRS_FOR_NEW_TIMESTEP_START = 9,
    CREATE_VARS_AND_ATTRS_FOR_NEW_TIMESTEP_DONE = 10,
    CREATE_TIMESTEP_DONE = 11,

    CREATE_AND_ACTIVATE_TIMESTEP_DONE = 12,
    CREATE_ALL_TIMESTEPS_DONE = 13,
    WRITING_DONE = 14,
    WRITING_DONE_FOR_ALL_PROCS_START_CLEANUP = 15,
    SERVER_SHUTDOWN_DONE = 16,
    DIRMAN_SHUTDOWN_DONE = 17,

    CREATE_NEW_RUN_START = 18,
    CREATE_NEW_RUN_DONE = 19,
    CREATE_TYPES_START = 20,
    CREATE_TYPES_DONE = 21,

  	CREATE_VARS_START = 22,
  	CREATE_VARS_DONE = 23,
  	CREATE_VAR_ATTRS_START = 24,
  	CREATE_VAR_ATTRS_DONE = 25,

    // CREATE_VAR_AND_ATTRS_FOR_NEW_VAR_START = 22,
    // CREATE_VAR_ATTRS_FOR_NEW_VAR_START = 23,
    // CREATE_NEW_VAR_ATTR_START = 24,
    // VAR_ATTR_INIT_DONE = 25,

    // CREATE_NEW_VAR_ATTR_DONE = 26,
    // CREATE_VAR_ATTRS_FOR_NEW_VAR_DONE = 27,
    GATHER_ATTRS_START = 26,
    GATHER_ATTRS_DONE = 27,

    CREATE_TIMESTEP_ATTRS_START = 28,
    GATHER_DONE_PROC_MAX_MIN_FIND_START = 29,
    PROC_MAX_MIN_FIND_DONE = 30,
    CREATE_TIMESTEP_ATTRS_DONE = 31,

    ACTIVATE_TIMESTEP_COMPONENTS_START = 32,
    ACTIVATE_TIMESTEP_COMPONENTS_DONE = 33,

    CREATE_RUN_ATTRS_START = 34,
    TIMESTEP_MAX_MIN_FIND_START = 35,
    TIMESTEP_MAX_MIN_FIND_DONE = 36,
    CREATE_RUN_ATTRS_DONE = 37,

   	INSERT_VAR_ATTRS_COLLECTIVE_START = 38,
   	INSERT_VAR_ATTRS_COLLECTIVE_DONE = 39,
};


// #ifndef CLIENTTIMINGCONSTANTSWRITECLASSPROJ_HH
// #define CLIENTTIMINGCONSTANTSWRITECLASSPROJ_HH
// //unsigned short -> max value: 65535
// enum CLIENT_TIMING_CONSTANTS_WRITE : unsigned short {
//     // ERR_ARGC = 10000,
//     // ERR_DIRMAN = 10001,
//     ERR_CREATE_TIMESTEP = 10002,
//     ERR_CREATE_RUN = 10003,
//     ERR_ACTIVATE_RUN = 10004,
//     ERR_CREATE_TYPE = 10005,

//     ERR_CREATE_TYPE_BATCH = 10006,
//     ERR_ACTIVATE_TYPE = 10007,
//     ERR_CREATE_VAR = 10008,
//     ERR_CREATE_VAR_BATCH = 10009,
//     ERR_TYPE_COMPARE = 10010,
//     ERR_INSERT_VAR_ATTR = 10011,

//     ERR_INSERT_VAR_ATTR_BATCH = 10012,
//     ERR_INSERT_TIMESTEP_ATTR_BATCH = 10013,
//     ERR_INSERT_TIMESTEP_ATTR = 10014,
//     ERR_ACTIVATE_TIMESTEP = 10015,
//     ERR_ACTIVATE_VAR = 10016,
//     ERR_ACTIVATE_VAR_ATTR = 10017,

//     ERR_ACTIVATE_TIMESTEP_ATTR = 10018,
//     ERR_INSERT_RUN_ATTR_BATCH = 10019,
//     ERR_INSERT_RUN_ATTR = 10020,
//     ERR_ACTIVATE_RUN_ATTR = 10021,

//     // PROGRAM_START = 0,
//     // MPI_INIT_DONE = 1,
//     METADATA_CLIENT_INIT_DONE = 2,
//     INIT_VARS_DONE = 3,
//     DIRMAN_SETUP_DONE = 4,
//     SERVER_SETUP_DONE_INIT_DONE = 5,

//     WRITING_START = 6,
//     CREATE_TIMESTEPS_START = 7,
//     CREATE_NEW_TIMESTEP_START = 8,
//     CREATE_VARS_AND_ATTRS_FOR_NEW_TIMESTEP_START = 9,
//     CREATE_VARS_AND_ATTRS_FOR_NEW_TIMESTEP_DONE = 10,
//     CREATE_TIMESTEP_DONE = 11,

//     CREATE_AND_ACTIVATE_TIMESTEP_DONE = 12,
//     CREATE_ALL_TIMESTEPS_DONE = 13,
//     WRITING_DONE = 14,
//     WRITING_DONE_FOR_ALL_PROCS_START_CLEANUP = 15,
//     SERVER_SHUTDOWN_DONE = 16,
//     DIRMAN_SHUTDOWN_DONE = 17,

//     GENERATE_START = 18,
//     GENERATE_NEW_RUN_START = 19,
//     GENERATE_NEW_RUN_DONE = 20,
//     GENERATE_TIMESTEPS_START = 21,
//     GENERATE_TIMESTEPS_DONE = 22,
//     GENERATE_TYPES_START = 23,
//     GENERATE_TYPES_DONE = 24,
//     GENERATE_VARS_START = 25,
//     GENERATE_VARS_DONE = 26,
//     GENERATE_VAR_ATTRS_START  = 27,
//     GENERATE_VAR_ATTRS_DONE = 28,
//     GENERATE_TIMESTEP_ATTRS_START = 29,
//     GENERATE_TIMESTEP_ATTRS_DONE = 30,
//     GENERATE_RUN_ATTRS_START = 31,
//     GENERATE_RUN_ATTRS_DONE = 32,
//     GENERATE_DONE = 33,


//     CREATE_NEW_RUN_START = 34,
//     CREATE_NEW_RUN_DONE = 35,
//     CREATE_TYPES_START = 36,
//     CREATE_TYPES_DONE = 37,

//     CREATE_VARS_START = 38,
//     CREATE_VARS_DONE = 39,
//     CREATE_VAR_ATTRS_START = 40,
//     CREATE_VAR_ATTRS_DONE = 41,

//     // CREATE_VAR_AND_ATTRS_FOR_NEW_VAR_START = 22,
//     // CREATE_VAR_ATTRS_FOR_NEW_VAR_START = 23,
//     // CREATE_NEW_VAR_ATTR_START = 24,
//     // VAR_ATTR_INIT_DONE = 25,

//     // CREATE_NEW_VAR_ATTR_DONE = 26,
//     // CREATE_VAR_ATTRS_FOR_NEW_VAR_DONE = 27,
//     GATHER_ATTRS_START = 42,
//     GATHER_ATTRS_DONE = 43,

//     CREATE_TIMESTEP_ATTRS_START = 44,
//     GATHER_DONE_PROC_MAX_MIN_FIND_START = 45,
//     PROC_MAX_MIN_FIND_DONE = 46,
//     CREATE_TIMESTEP_ATTRS_DONE = 47,

//     ACTIVATE_TIMESTEP_COMPONENTS_START = 48,
//     ACTIVATE_TIMESTEP_COMPONENTS_DONE = 49,

//     CREATE_RUN_ATTRS_START = 50,
//     TIMESTEP_MAX_MIN_FIND_START = 51,
//     TIMESTEP_MAX_MIN_FIND_DONE = 52,
//     CREATE_RUN_ATTRS_DONE = 53,

//     INSERT_VAR_ATTRS_COLLECTIVE_START = 52,
//     INSERT_VAR_ATTRS_COLLECTIVE_DONE = 53,
// };

#endif //#ifndef CLIENTTIMINGCONSTANTSWRITECLASSPROJ_HH

