



#ifndef CLIENTTIMINGCONSTANTSREADHDF5_HH
#define CLIENTTIMINGCONSTANTSREADHDF5_HH

//unsigned short -> max value: 65535
enum CLIENT_TIMING_CONSTANTS_READ : unsigned short {
    ERR_ARGC = 10000,

    PROGRAM_START = 0,
    MPI_INIT_DONE = 1,
    INIT_VARS_DONE = 2,

    READING_INIT_START = 3,
    READING_START = 4,
    FIND_VARS_DONE = 5,
    READING_PATTERNS_START = 6,
    READING_PATTERNS_DONE = 7,

    EXTRA_TESTING_START = 8,
    EXTRA_TESTING_DONE = 9,
    READING_DONE = 10,

    READ_PATTERN_1_START = 11,
    READ_PATTERN_1_START_CATALOGING_VAR_ATTRS = 12,
    READ_PATTERN_1_DONE_CATALOGING_VAR_ATTRS = 13,
    READ_PATTERN_1_DONE = 14,

    READ_PATTERN_2_START = 15,
    READ_PATTERN_2_START_CATALOGING_VAR_ATTRS = 16,
    READ_PATTERN_2_DONE_CATALOGING_VAR_ATTRS = 17,
    READ_PATTERN_2_DONE = 18,

    READ_PATTERN_3_START = 25,
    READ_PATTERN_3_START_CATALOGING_VAR_ATTRS = 26,
    READ_PATTERN_3_DONE_CATALOGING_VAR_ATTRS = 27,
    READ_PATTERN_3_DONE = 28,
   
    READ_PATTERN_4_START = 35,
    READ_PATTERN_4_START_CATALOGING_VAR_ATTRS = 36,
    READ_PATTERN_4_DONE_CATALOGING_VAR_ATTRS = 37,
    READ_PATTERN_4_DONE = 38,

    READ_PATTERN_5_START = 39,
    READ_PATTERN_5_START_CATALOGING_VAR_ATTRS = 40,
    READ_PATTERN_5_DONE_CATALOGING_VAR_ATTRS = 41,
    READ_PATTERN_5_DONE = 42,

    READ_PATTERN_6_START = 43,
    READ_PATTERN_6_START_CATALOGING_VAR_ATTRS = 44,
    READ_PATTERN_6_DONE_CATALOGING_VAR_ATTRS = 45,
    READ_PATTERN_6_DONE = 46,

    BCAST_ENTRIES_COLLECTIVE_START = 47,
    BCAST_ENTRIES_COLLECTIVE_DONE = 48,

	CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_COLLECTIVE_START = 13700,	
	CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_COLLECTIVE_DONE = 13701,	
    
    CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_COLLECTIVE_START = 13900,
    CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_COLLECTIVE_DONE = 13901,

	CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_COLLECTIVE_START = 16400,	
	CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_COLLECTIVE_DONE	= 16401,	


};

#endif 

