


#ifndef SERVERTIMINGCONSTANTS_HH
#define SERVERTIMINGCONSTANTS_HH

//unsigned short -> max value: 65535
enum SERVER_TIMING_CONSTANTS : unsigned short {

//10000 - errors
    ERR_ARGC = 10000,
    ERR_DIRMAN = 10001,
    ERR_DB_SETUP = 10002,

//md_server
    PROGRAM_START = 0,
    MPI_INIT_DONE = 1,
    REGISTER_OPS_DONE = 2,
    DB_SETUP_START = 3,
    DB_SETUP_DONE = 4,
    DIRMAN_SETUP_DONE_INIT_DONE = 5,
    SHUTDOWN_START = 6,
    DB_ANALYSIS_DONE = 7,
    DB_CLOSED_SHUTDOWN_DONE = 8,

    DB_CREATE_INDICES_START = 10,
    DB_CREATE_INDICES_DONE = 11,

    DB_SIZES = 97,
    CLOCK_TIMES_NEW_PROC = 98,
    CLOCK_TIMES_DONE = 99,

    // DB_LOAD_START = 992,
    // DB_LOAD_DONE = 993,
   	// DB_OUTPUT_START = 994,
    // DB_OUTPUT_DONE = 995,
   	// DB_OUTPUT_INCREMENTAL_NEW_FILE_START = 996,
    // DB_OUTPUT_INCREMENTAL_NEW_FILE_DONE = 997,
   	// DB_OUTPUT_INCREMENTAL_START = 998,
    // DB_OUTPUT_INCREMENTAL_DONE = 999,

    DB_RESET_START = 980,
    DB_RESET_DONE = 981,
    DB_LOAD_START = 982,
    DB_LOAD_DONE = 983,
    DB_COMPACT_AND_OUTPUT_START = 984,
    DB_COMPACT_AND_OUTPUT_DONE = 985,
    DB_COMPACT_START = 986,
    DB_COMPACT_DONE = 987,
    DB_CHECKPT_COPY_START = 988,
    DB_CHECKPT_COPY_DONE = 989,
    DB_CHECKPT_INCREMENTAL_OUTPUT_START = 990,
    DB_CHECKPT_INCREMENTAL_OUTPUT_DONE = 991,
	DB_CHECKPT_COPY_AND_DELETE_START = 992,
    DB_CHECKPT_COPY_AND_DELETE_DONE = 993,
	DB_CHECKPT_COPY_AND_RESET_START = 994,
    DB_CHECKPT_COPY_AND_RESET_DONE = 995,
	DB_CHECKPT_INCREMENTAL_OUTPUT_AND_DELETE_START = 996,
    DB_CHECKPT_INCREMENTAL_OUTPUT_AND_DELETE_DONE = 997,
	DB_CHECKPT_INCREMENTAL_OUTPUT_AND_RESET_START = 998,
    DB_CHECKPT_INCREMENTAL_OUTPUT_AND_RESET_DONE = 999,


//var ops, note: client side is from **00-**49
//
    OP_ACTIVATE_RUN_START = 1050,
    OP_ACTIVATE_RUN_DEARCHIVE_MSG_FROM_CLIENT = 1051,
    OP_ACTIVATE_RUN_MD_ACTIVATE_RUN_STUB = 1052,
    OP_ACTIVATE_RUN_SERIALIZE_MSG_FOR_CLIENT = 1053,
    OP_ACTIVATE_RUN_CREATE_MSG_FOR_CLIENT = 1054,
    OP_ACTIVATE_RUN_SEND_MSG_TO_CLIENT_OP_DONE = 1055,

//
    OP_ACTIVATE_TIMESTEP_START = 1150,
    OP_ACTIVATE_TIMESTEP_DEARCHIVE_MSG_FROM_CLIENT = 1151,
    OP_ACTIVATE_TIMESTEP_MD_ACTIVATE_TIMESTEP_STUB = 1152,
    OP_ACTIVATE_TIMESTEP_SERIALIZE_MSG_FOR_CLIENT = 1153,
    OP_ACTIVATE_TIMESTEP_CREATE_MSG_FOR_CLIENT = 1154,
    OP_ACTIVATE_TIMESTEP_SEND_MSG_TO_CLIENT_OP_DONE = 1155,

//
    OP_ACTIVATE_VAR_START = 1250,
    OP_ACTIVATE_VAR_DEARCHIVE_MSG_FROM_CLIENT = 1251,
    OP_ACTIVATE_VAR_MD_ACTIVATE_VAR_STUB = 1252,
    OP_ACTIVATE_VAR_SERIALIZE_MSG_FOR_CLIENT = 1253,
    OP_ACTIVATE_VAR_CREATE_MSG_FOR_CLIENT = 1254,
    OP_ACTIVATE_VAR_SEND_MSG_TO_CLIENT_OP_DONE = 1255,

//
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_START = 1350,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_DEARCHIVE_MSG_FROM_CLIENT = 1351,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_STUB = 1352,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SERIALIZE_MSG_FOR_CLIENT = 1353,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_CREATE_MSG_FOR_CLIENT = 1354,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SEND_MSG_TO_CLIENT_OP_DONE = 1355,

//
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_START = 1450,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_DEARCHIVE_MSG_FROM_CLIENT = 1451,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_STUB = 1452,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_SERIALIZE_MSG_FOR_CLIENT = 1453,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_CREATE_MSG_FOR_CLIENT = 1454,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_SEND_MSG_TO_CLIENT_OP_DONE = 1455,

//
    OP_CATALOG_RUN_START = 1550,
    OP_CATALOG_RUN_DEARCHIVE_MSG_FROM_CLIENT = 1551,
    OP_CATALOG_RUN_MD_CATALOG_RUN_STUB = 1552,
    OP_CATALOG_RUN_SERIALIZE_MSG_FOR_CLIENT = 1553,
    OP_CATALOG_RUN_CREATE_MSG_FOR_CLIENT = 1554,
    OP_CATALOG_RUN_SEND_MSG_TO_CLIENT_OP_DONE = 1555,

//
    OP_CATALOG_TIMESTEP_START = 1650,
    OP_CATALOG_TIMESTEP_DEARCHIVE_MSG_FROM_CLIENT = 1651,
    OP_CATALOG_TIMESTEP_MD_CATALOG_TIMESTEP_STUB = 1652,
    OP_CATALOG_TIMESTEP_SERIALIZE_MSG_FOR_CLIENT = 1653,
    OP_CATALOG_TIMESTEP_CREATE_MSG_FOR_CLIENT = 1654,
    OP_CATALOG_TIMESTEP_SEND_MSG_TO_CLIENT_OP_DONE = 1655,

//
    OP_CATALOG_VAR_START = 1750,
    OP_CATALOG_VAR_DEARCHIVE_MSG_FROM_CLIENT = 1751,
    OP_CATALOG_VAR_MD_CATALOG_VAR_STUB = 1752,
    OP_CATALOG_VAR_SERIALIZE_MSG_FOR_CLIENT = 1753,
    OP_CATALOG_VAR_CREATE_MSG_FOR_CLIENT = 1754,
    OP_CATALOG_VAR_SEND_MSG_TO_CLIENT_OP_DONE = 1755,

//
    OP_CHECKPOINT_DATABASE_START = 1850,
    OP_CHECKPOINT_DATABASE_DEARCHIVE_MSG_FROM_CLIENT = 1851,
    OP_CHECKPOINT_DATABASE_MD_CHECKPOINT_DATABASE_STUB = 1852,
    OP_CHECKPOINT_DATABASE_SERIALIZE_MSG_FOR_CLIENT = 1853,
    OP_CHECKPOINT_DATABASE_CREATE_MSG_FOR_CLIENT = 1854,
    OP_CHECKPOINT_DATABASE_SEND_MSG_TO_CLIENT_OP_DONE = 1855,

//
    OP_CREATE_RUN_START = 1950,
    OP_CREATE_RUN_DEARCHIVE_MSG_FROM_CLIENT = 1951,
    OP_CREATE_RUN_MD_CREATE_RUN_STUB = 1952,
    OP_CREATE_RUN_SERIALIZE_MSG_FOR_CLIENT = 1953,
    OP_CREATE_RUN_CREATE_MSG_FOR_CLIENT = 1954,
    OP_CREATE_RUN_SEND_MSG_TO_CLIENT_OP_DONE = 1955,

//
    OP_CREATE_TIMESTEP_START = 2050,
    OP_CREATE_TIMESTEP_DEARCHIVE_MSG_FROM_CLIENT = 2051,
    OP_CREATE_TIMESTEP_MD_CREATE_TIMESTEP_STUB = 2052,
    OP_CREATE_TIMESTEP_SERIALIZE_MSG_FOR_CLIENT = 2053,
    OP_CREATE_TIMESTEP_CREATE_MSG_FOR_CLIENT = 2054,
    OP_CREATE_TIMESTEP_SEND_MSG_TO_CLIENT_OP_DONE = 2055,

//
    OP_CREATE_VAR_START = 2150,
    OP_CREATE_VAR_DEARCHIVE_MSG_FROM_CLIENT = 2151,
    OP_CREATE_VAR_MD_CREATE_VAR_STUB = 2152,
    OP_CREATE_VAR_SERIALIZE_MSG_FOR_CLIENT = 2153,
    OP_CREATE_VAR_CREATE_MSG_FOR_CLIENT = 2154,
    OP_CREATE_VAR_SEND_MSG_TO_CLIENT_OP_DONE = 2155,

//
    OP_CREATE_VAR_BATCH_START = 2250,
    OP_CREATE_VAR_BATCH_DEARCHIVE_MSG_FROM_CLIENT = 2251,
    OP_CREATE_VAR_BATCH_MD_CREATE_VAR_BATCH_STUB = 2252,
    OP_CREATE_VAR_BATCH_SERIALIZE_MSG_FOR_CLIENT = 2253,
    OP_CREATE_VAR_BATCH_CREATE_MSG_FOR_CLIENT = 2254,
    OP_CREATE_VAR_BATCH_SEND_MSG_TO_CLIENT_OP_DONE = 2255,

//
    OP_DELETE_ALL_VARS_WITH_SUBSTR_START = 2350,
    OP_DELETE_ALL_VARS_WITH_SUBSTR_DEARCHIVE_MSG_FROM_CLIENT = 2351,
    OP_DELETE_ALL_VARS_WITH_SUBSTR_MD_DELETE_ALL_VARS_WITH_SUBSTR_STUB = 2352,
    OP_DELETE_ALL_VARS_WITH_SUBSTR_SERIALIZE_MSG_FOR_CLIENT = 2353,
    OP_DELETE_ALL_VARS_WITH_SUBSTR_CREATE_MSG_FOR_CLIENT = 2354,
    OP_DELETE_ALL_VARS_WITH_SUBSTR_SEND_MSG_TO_CLIENT_OP_DONE = 2355,

//
    OP_DELETE_RUN_BY_ID_START = 2450,
    OP_DELETE_RUN_BY_ID_DEARCHIVE_MSG_FROM_CLIENT = 2451,
    OP_DELETE_RUN_BY_ID_MD_DELETE_RUN_BY_ID_STUB = 2452,
    OP_DELETE_RUN_BY_ID_SERIALIZE_MSG_FOR_CLIENT = 2453,
    OP_DELETE_RUN_BY_ID_CREATE_MSG_FOR_CLIENT = 2454,
    OP_DELETE_RUN_BY_ID_SEND_MSG_TO_CLIENT_OP_DONE = 2455,

//
    OP_DELETE_TIMESTEP_BY_ID_START = 2550,
    OP_DELETE_TIMESTEP_BY_ID_DEARCHIVE_MSG_FROM_CLIENT = 2551,
    OP_DELETE_TIMESTEP_BY_ID_MD_DELETE_TIMESTEP_BY_ID_STUB = 2552,
    OP_DELETE_TIMESTEP_BY_ID_SERIALIZE_MSG_FOR_CLIENT = 2553,
    OP_DELETE_TIMESTEP_BY_ID_CREATE_MSG_FOR_CLIENT = 2554,
    OP_DELETE_TIMESTEP_BY_ID_SEND_MSG_TO_CLIENT_OP_DONE = 2555,

//
    OP_DELETE_VAR_BY_ID_START = 2650,
    OP_DELETE_VAR_BY_ID_DEARCHIVE_MSG_FROM_CLIENT = 2651,
    OP_DELETE_VAR_BY_ID_MD_DELETE_VAR_BY_ID_STUB = 2652,
    OP_DELETE_VAR_BY_ID_SERIALIZE_MSG_FOR_CLIENT = 2653,
    OP_DELETE_VAR_BY_ID_CREATE_MSG_FOR_CLIENT = 2654,
    OP_DELETE_VAR_BY_ID_SEND_MSG_TO_CLIENT_OP_DONE = 2655,

//
    OP_DELETE_VAR_BY_NAME_PATH_VER_START = 2750,
    OP_DELETE_VAR_BY_NAME_PATH_VER_DEARCHIVE_MSG_FROM_CLIENT = 2751,
    OP_DELETE_VAR_BY_NAME_PATH_VER_MD_DELETE_VAR_BY_NAME_PATH_VER_STUB = 2752,
    OP_DELETE_VAR_BY_NAME_PATH_VER_SERIALIZE_MSG_FOR_CLIENT = 2753,
    OP_DELETE_VAR_BY_NAME_PATH_VER_CREATE_MSG_FOR_CLIENT = 2754,
    OP_DELETE_VAR_BY_NAME_PATH_VER_SEND_MSG_TO_CLIENT_OP_DONE = 2755,

//
    OP_PROCESSING_START = 2850,
    OP_PROCESSING_DEARCHIVE_MSG_FROM_CLIENT = 2851,
    OP_PROCESSING_MD_PROCESSING_STUB = 2852,
    OP_PROCESSING_SERIALIZE_MSG_FOR_CLIENT = 2853,
    OP_PROCESSING_CREATE_MSG_FOR_CLIENT = 2854,
    OP_PROCESSING_SEND_MSG_TO_CLIENT_OP_DONE = 2855,

//
    OP_ACTIVATE_RUN_ATTRIBUTE_START = 2950,
    OP_ACTIVATE_RUN_ATTRIBUTE_DEARCHIVE_MSG_FROM_CLIENT = 2951,
    OP_ACTIVATE_RUN_ATTRIBUTE_MD_ACTIVATE_RUN_ATTRIBUTE_STUB = 2952,
    OP_ACTIVATE_RUN_ATTRIBUTE_SERIALIZE_MSG_FOR_CLIENT = 2953,
    OP_ACTIVATE_RUN_ATTRIBUTE_CREATE_MSG_FOR_CLIENT = 2954,
    OP_ACTIVATE_RUN_ATTRIBUTE_SEND_MSG_TO_CLIENT_OP_DONE = 2955,

//
    OP_ACTIVATE_TIMESTEP_ATTRIBUTE_START = 3050,
    OP_ACTIVATE_TIMESTEP_ATTRIBUTE_DEARCHIVE_MSG_FROM_CLIENT = 3051,
    OP_ACTIVATE_TIMESTEP_ATTRIBUTE_MD_ACTIVATE_TIMESTEP_ATTRIBUTE_STUB = 3052,
    OP_ACTIVATE_TIMESTEP_ATTRIBUTE_SERIALIZE_MSG_FOR_CLIENT = 3053,
    OP_ACTIVATE_TIMESTEP_ATTRIBUTE_CREATE_MSG_FOR_CLIENT = 3054,
    OP_ACTIVATE_TIMESTEP_ATTRIBUTE_SEND_MSG_TO_CLIENT_OP_DONE = 3055,

//
    OP_ACTIVATE_TYPE_START = 3150,
    OP_ACTIVATE_TYPE_DEARCHIVE_MSG_FROM_CLIENT = 3151,
    OP_ACTIVATE_TYPE_MD_ACTIVATE_TYPE_STUB = 3152,
    OP_ACTIVATE_TYPE_SERIALIZE_MSG_FOR_CLIENT = 3153,
    OP_ACTIVATE_TYPE_CREATE_MSG_FOR_CLIENT = 3154,
    OP_ACTIVATE_TYPE_SEND_MSG_TO_CLIENT_OP_DONE = 3155,

//
    OP_ACTIVATE_VAR_ATTRIBUTE_START = 3250,
    OP_ACTIVATE_VAR_ATTRIBUTE_DEARCHIVE_MSG_FROM_CLIENT = 3251,
    OP_ACTIVATE_VAR_ATTRIBUTE_MD_ACTIVATE_VAR_ATTRIBUTE_STUB = 3252,
    OP_ACTIVATE_VAR_ATTRIBUTE_SERIALIZE_MSG_FOR_CLIENT = 3253,
    OP_ACTIVATE_VAR_ATTRIBUTE_CREATE_MSG_FOR_CLIENT = 3254,
    OP_ACTIVATE_VAR_ATTRIBUTE_SEND_MSG_TO_CLIENT_OP_DONE = 3255,

//
    OP_CATALOG_ALL_RUN_ATTRIBUTES_START = 3350,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_DEARCHIVE_MSG_FROM_CLIENT = 3351,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_MD_CATALOG_ALL_RUN_ATTRIBUTES_STUB = 3352,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_SERIALIZE_MSG_FOR_CLIENT = 3353,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_CREATE_MSG_FOR_CLIENT = 3354,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_SEND_MSG_TO_CLIENT_OP_DONE = 3355,

//
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_START = 3450,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_DEARCHIVE_MSG_FROM_CLIENT = 3451,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_MD_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_STUB = 3452,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_SERIALIZE_MSG_FOR_CLIENT = 3453,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_CREATE_MSG_FOR_CLIENT = 3454,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_SEND_MSG_TO_CLIENT_OP_DONE = 3455,

//
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_START = 3550,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_DEARCHIVE_MSG_FROM_CLIENT = 3551,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_MD_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_STUB = 3552,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_SERIALIZE_MSG_FOR_CLIENT = 3553,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_CREATE_MSG_FOR_CLIENT = 3554,
    OP_CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_RANGE_SEND_MSG_TO_CLIENT_OP_DONE = 3555,

//
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_START = 3650,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_DEARCHIVE_MSG_FROM_CLIENT = 3651,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_STUB = 3652,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_SERIALIZE_MSG_FOR_CLIENT = 3653,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_CREATE_MSG_FOR_CLIENT = 3654,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_SEND_MSG_TO_CLIENT_OP_DONE = 3655,

//
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_START = 3750,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_DEARCHIVE_MSG_FROM_CLIENT = 3751,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_STUB = 3752,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_SERIALIZE_MSG_FOR_CLIENT = 3753,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_CREATE_MSG_FOR_CLIENT = 3754,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_SEND_MSG_TO_CLIENT_OP_DONE = 3755,

//
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_START = 3850,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_DEARCHIVE_MSG_FROM_CLIENT = 3851,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_MD_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_STUB = 3852,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_SERIALIZE_MSG_FOR_CLIENT = 3853,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_CREATE_MSG_FOR_CLIENT = 3854,
    OP_CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_RANGE_SEND_MSG_TO_CLIENT_OP_DONE = 3855,

//
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_START = 3950,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DEARCHIVE_MSG_FROM_CLIENT = 3951,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_STUB = 3952,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SERIALIZE_MSG_FOR_CLIENT = 3953,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_CREATE_MSG_FOR_CLIENT = 3954,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SEND_MSG_TO_CLIENT_OP_DONE = 3955,

//
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_START = 4050,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_DEARCHIVE_MSG_FROM_CLIENT = 4051,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_STUB = 4052,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_SERIALIZE_MSG_FOR_CLIENT = 4053,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_CREATE_MSG_FOR_CLIENT = 4054,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_SEND_MSG_TO_CLIENT_OP_DONE = 4055,

//
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_START = 4150,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_DEARCHIVE_MSG_FROM_CLIENT = 4151,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_STUB = 4152,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_SERIALIZE_MSG_FOR_CLIENT = 4153,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_CREATE_MSG_FOR_CLIENT = 4154,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_SEND_MSG_TO_CLIENT_OP_DONE = 4155,

//
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_START = 4250,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_DEARCHIVE_MSG_FROM_CLIENT = 4251,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_STUB = 4252,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_SERIALIZE_MSG_FOR_CLIENT = 4253,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_CREATE_MSG_FOR_CLIENT = 4254,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_SEND_MSG_TO_CLIENT_OP_DONE = 4255,

//
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_START = 4350,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DEARCHIVE_MSG_FROM_CLIENT = 4351,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_STUB = 4352,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_SERIALIZE_MSG_FOR_CLIENT = 4353,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_CREATE_MSG_FOR_CLIENT = 4354,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_SEND_MSG_TO_CLIENT_OP_DONE = 4355,

//
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_START = 4450,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_DEARCHIVE_MSG_FROM_CLIENT = 4451,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_STUB = 4452,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_SERIALIZE_MSG_FOR_CLIENT = 4453,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_CREATE_MSG_FOR_CLIENT = 4454,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_SEND_MSG_TO_CLIENT_OP_DONE = 4455,

//
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_START = 4550,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_DEARCHIVE_MSG_FROM_CLIENT = 4551,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_STUB = 4552,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_SERIALIZE_MSG_FOR_CLIENT = 4553,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_CREATE_MSG_FOR_CLIENT = 4554,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_SEND_MSG_TO_CLIENT_OP_DONE = 4555,

//
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_START = 4650,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_DEARCHIVE_MSG_FROM_CLIENT = 4651,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_MD_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_STUB = 4652,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_SERIALIZE_MSG_FOR_CLIENT = 4653,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_CREATE_MSG_FOR_CLIENT = 4654,
    OP_CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_SEND_MSG_TO_CLIENT_OP_DONE = 4655,

//
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_START = 4750,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_DEARCHIVE_MSG_FROM_CLIENT = 4751,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_STUB = 4752,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_SERIALIZE_MSG_FOR_CLIENT = 4753,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_CREATE_MSG_FOR_CLIENT = 4754,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_SEND_MSG_TO_CLIENT_OP_DONE = 4755,

//
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_START = 4850,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_DEARCHIVE_MSG_FROM_CLIENT = 4851,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_STUB = 4852,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_SERIALIZE_MSG_FOR_CLIENT = 4853,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_CREATE_MSG_FOR_CLIENT = 4854,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_SEND_MSG_TO_CLIENT_OP_DONE = 4855,

//
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_START = 4950,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_DEARCHIVE_MSG_FROM_CLIENT = 4951,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_STUB = 4952,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_SERIALIZE_MSG_FOR_CLIENT = 4953,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_CREATE_MSG_FOR_CLIENT = 4954,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_SEND_MSG_TO_CLIENT_OP_DONE = 4955,

//
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_START = 5050,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_DEARCHIVE_MSG_FROM_CLIENT = 5051,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_STUB = 5052,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_SERIALIZE_MSG_FOR_CLIENT = 5053,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_CREATE_MSG_FOR_CLIENT = 5054,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_SEND_MSG_TO_CLIENT_OP_DONE = 5055,

//
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_START = 5150,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_DEARCHIVE_MSG_FROM_CLIENT = 5151,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_MD_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_STUB = 5152,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_SERIALIZE_MSG_FOR_CLIENT = 5153,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_CREATE_MSG_FOR_CLIENT = 5154,
    OP_CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_SEND_MSG_TO_CLIENT_OP_DONE = 5155,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_START = 5250,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_DEARCHIVE_MSG_FROM_CLIENT = 5251,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_MD_CATALOG_ALL_VAR_ATTRIBUTES_STUB = 5252,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_SERIALIZE_MSG_FOR_CLIENT = 5253,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_CREATE_MSG_FOR_CLIENT = 5254,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_SEND_MSG_TO_CLIENT_OP_DONE = 5255,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_START = 5350,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_DEARCHIVE_MSG_FROM_CLIENT = 5351,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_STUB = 5352,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_SERIALIZE_MSG_FOR_CLIENT = 5353,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_CREATE_MSG_FOR_CLIENT = 5354,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_SEND_MSG_TO_CLIENT_OP_DONE = 5355,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_START = 5450,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_DEARCHIVE_MSG_FROM_CLIENT = 5451,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_STUB = 5452,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_SERIALIZE_MSG_FOR_CLIENT = 5453,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_CREATE_MSG_FOR_CLIENT = 5454,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_ID_SEND_MSG_TO_CLIENT_OP_DONE = 5455,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_START = 5550,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_DEARCHIVE_MSG_FROM_CLIENT = 5551,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_STUB = 5552,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_SERIALIZE_MSG_FOR_CLIENT = 5553,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_CREATE_MSG_FOR_CLIENT = 5554,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_BY_NAME_VER_SEND_MSG_TO_CLIENT_OP_DONE = 5555,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_START = 5650,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_DEARCHIVE_MSG_FROM_CLIENT = 5651,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_STUB = 5652,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_SERIALIZE_MSG_FOR_CLIENT = 5653,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_CREATE_MSG_FOR_CLIENT = 5654,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_ID_SEND_MSG_TO_CLIENT_OP_DONE = 5655,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_START = 5750,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_DEARCHIVE_MSG_FROM_CLIENT = 5751,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_STUB = 5752,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_SERIALIZE_MSG_FOR_CLIENT = 5753,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_CREATE_MSG_FOR_CLIENT = 5754,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_BY_NAME_VER_SEND_MSG_TO_CLIENT_OP_DONE = 5755,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_START = 5850,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_DEARCHIVE_MSG_FROM_CLIENT = 5851,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_STUB = 5852,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_SERIALIZE_MSG_FOR_CLIENT = 5853,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_CREATE_MSG_FOR_CLIENT = 5854,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_ID_SEND_MSG_TO_CLIENT_OP_DONE = 5855,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_START = 5950,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_DEARCHIVE_MSG_FROM_CLIENT = 5951,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_STUB = 5952,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_SERIALIZE_MSG_FOR_CLIENT = 5953,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_CREATE_MSG_FOR_CLIENT = 5954,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_BY_NAME_VER_SEND_MSG_TO_CLIENT_OP_DONE = 5955,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_START = 6050,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_DEARCHIVE_MSG_FROM_CLIENT = 6051,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_STUB = 6052,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_SERIALIZE_MSG_FOR_CLIENT = 6053,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_CREATE_MSG_FOR_CLIENT = 6054,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_ID_SEND_MSG_TO_CLIENT_OP_DONE = 6055,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_START = 6150,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_DEARCHIVE_MSG_FROM_CLIENT = 6151,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_STUB = 6152,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_SERIALIZE_MSG_FOR_CLIENT = 6153,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_CREATE_MSG_FOR_CLIENT = 6154,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_BY_NAME_VER_SEND_MSG_TO_CLIENT_OP_DONE = 6155,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_START = 6250,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_DEARCHIVE_MSG_FROM_CLIENT = 6251,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_STUB = 6252,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_SERIALIZE_MSG_FOR_CLIENT = 6253,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_CREATE_MSG_FOR_CLIENT = 6254,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_RANGE_SEND_MSG_TO_CLIENT_OP_DONE = 6255,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_START = 6350,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_DEARCHIVE_MSG_FROM_CLIENT = 6351,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_STUB = 6352,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_SERIALIZE_MSG_FOR_CLIENT = 6353,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_CREATE_MSG_FOR_CLIENT = 6354,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_RANGE_SEND_MSG_TO_CLIENT_OP_DONE = 6355,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_START = 6450,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DEARCHIVE_MSG_FROM_CLIENT = 6451,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_STUB = 6452,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_SERIALIZE_MSG_FOR_CLIENT = 6453,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_CREATE_MSG_FOR_CLIENT = 6454,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_SEND_MSG_TO_CLIENT_OP_DONE = 6455,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_START = 6550,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_DEARCHIVE_MSG_FROM_CLIENT = 6551,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_STUB = 6552,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_SERIALIZE_MSG_FOR_CLIENT = 6553,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_CREATE_MSG_FOR_CLIENT = 6554,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_SEND_MSG_TO_CLIENT_OP_DONE = 6555,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_START = 6650,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_DEARCHIVE_MSG_FROM_CLIENT = 6651,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_STUB = 6652,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_SERIALIZE_MSG_FOR_CLIENT = 6653,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_CREATE_MSG_FOR_CLIENT = 6654,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_RANGE_SEND_MSG_TO_CLIENT_OP_DONE = 6655,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_START = 6750,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_DEARCHIVE_MSG_FROM_CLIENT = 6751,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_STUB = 6752,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_SERIALIZE_MSG_FOR_CLIENT = 6753,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_CREATE_MSG_FOR_CLIENT = 6754,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_RANGE_SEND_MSG_TO_CLIENT_OP_DONE = 6755,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_START = 6850,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_DEARCHIVE_MSG_FROM_CLIENT = 6851,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_STUB = 6852,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_SERIALIZE_MSG_FOR_CLIENT = 6853,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_CREATE_MSG_FOR_CLIENT = 6854,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_ID_SEND_MSG_TO_CLIENT_OP_DONE = 6855,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_START = 6950,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_DEARCHIVE_MSG_FROM_CLIENT = 6951,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_STUB = 6952,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_SERIALIZE_MSG_FOR_CLIENT = 6953,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_CREATE_MSG_FOR_CLIENT = 6954,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_BY_NAME_VER_SEND_MSG_TO_CLIENT_OP_DONE = 6955,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_START = 7050,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_DEARCHIVE_MSG_FROM_CLIENT = 7051,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_STUB = 7052,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_SERIALIZE_MSG_FOR_CLIENT = 7053,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_CREATE_MSG_FOR_CLIENT = 7054,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_ID_SEND_MSG_TO_CLIENT_OP_DONE = 7055,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_START = 7150,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_DEARCHIVE_MSG_FROM_CLIENT = 7151,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_STUB = 7152,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_SERIALIZE_MSG_FOR_CLIENT = 7153,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_CREATE_MSG_FOR_CLIENT = 7154,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_BY_NAME_VER_SEND_MSG_TO_CLIENT_OP_DONE = 7155,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_START = 7250,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DEARCHIVE_MSG_FROM_CLIENT = 7251,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_STUB = 7252,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_SERIALIZE_MSG_FOR_CLIENT = 7253,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_CREATE_MSG_FOR_CLIENT = 7254,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_SEND_MSG_TO_CLIENT_OP_DONE = 7255,

//
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_START = 7350,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_DEARCHIVE_MSG_FROM_CLIENT = 7351,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_MD_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_STUB = 7352,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_SERIALIZE_MSG_FOR_CLIENT = 7353,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_CREATE_MSG_FOR_CLIENT = 7354,
    OP_CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_SEND_MSG_TO_CLIENT_OP_DONE = 7355,

//
    OP_CATALOG_TYPE_START = 7450,
    OP_CATALOG_TYPE_DEARCHIVE_MSG_FROM_CLIENT = 7451,
    OP_CATALOG_TYPE_MD_CATALOG_TYPE_STUB = 7452,
    OP_CATALOG_TYPE_SERIALIZE_MSG_FOR_CLIENT = 7453,
    OP_CATALOG_TYPE_CREATE_MSG_FOR_CLIENT = 7454,
    OP_CATALOG_TYPE_SEND_MSG_TO_CLIENT_OP_DONE = 7455,

//
    OP_CREATE_TYPE_START = 7550,
    OP_CREATE_TYPE_DEARCHIVE_MSG_FROM_CLIENT = 7551,
    OP_CREATE_TYPE_MD_CREATE_TYPE_STUB = 7552,
    OP_CREATE_TYPE_SERIALIZE_MSG_FOR_CLIENT = 7553,
    OP_CREATE_TYPE_CREATE_MSG_FOR_CLIENT = 7554,
    OP_CREATE_TYPE_SEND_MSG_TO_CLIENT_OP_DONE = 7555,

//
    OP_CREATE_TYPE_BATCH_START = 7650,
    OP_CREATE_TYPE_BATCH_DEARCHIVE_MSG_FROM_CLIENT = 7651,
    OP_CREATE_TYPE_BATCH_MD_CREATE_TYPE_BATCH_STUB = 7652,
    OP_CREATE_TYPE_BATCH_SERIALIZE_MSG_FOR_CLIENT = 7653,
    OP_CREATE_TYPE_BATCH_CREATE_MSG_FOR_CLIENT = 7654,
    OP_CREATE_TYPE_BATCH_SEND_MSG_TO_CLIENT_OP_DONE = 7655,

//
    OP_DELETE_TYPE_BY_ID_START = 7750,
    OP_DELETE_TYPE_BY_ID_DEARCHIVE_MSG_FROM_CLIENT = 7751,
    OP_DELETE_TYPE_BY_ID_MD_DELETE_TYPE_BY_ID_STUB = 7752,
    OP_DELETE_TYPE_BY_ID_SERIALIZE_MSG_FOR_CLIENT = 7753,
    OP_DELETE_TYPE_BY_ID_CREATE_MSG_FOR_CLIENT = 7754,
    OP_DELETE_TYPE_BY_ID_SEND_MSG_TO_CLIENT_OP_DONE = 7755,

//
    OP_DELETE_TYPE_BY_NAME_VER_START = 7850,
    OP_DELETE_TYPE_BY_NAME_VER_DEARCHIVE_MSG_FROM_CLIENT = 7851,
    OP_DELETE_TYPE_BY_NAME_VER_MD_DELETE_TYPE_BY_NAME_VER_STUB = 7852,
    OP_DELETE_TYPE_BY_NAME_VER_SERIALIZE_MSG_FOR_CLIENT = 7853,
    OP_DELETE_TYPE_BY_NAME_VER_CREATE_MSG_FOR_CLIENT = 7854,
    OP_DELETE_TYPE_BY_NAME_VER_SEND_MSG_TO_CLIENT_OP_DONE = 7855,

//
    OP_INSERT_RUN_ATTRIBUTE_START = 7950,
    OP_INSERT_RUN_ATTRIBUTE_DEARCHIVE_MSG_FROM_CLIENT = 7951,
    OP_INSERT_RUN_ATTRIBUTE_MD_INSERT_RUN_ATTRIBUTE_STUB = 7952,
    OP_INSERT_RUN_ATTRIBUTE_SERIALIZE_MSG_FOR_CLIENT = 7953,
    OP_INSERT_RUN_ATTRIBUTE_CREATE_MSG_FOR_CLIENT = 7954,
    OP_INSERT_RUN_ATTRIBUTE_SEND_MSG_TO_CLIENT_OP_DONE = 7955,

//
    OP_INSERT_RUN_ATTRIBUTE_BATCH_START = 8050,
    OP_INSERT_RUN_ATTRIBUTE_BATCH_DEARCHIVE_MSG_FROM_CLIENT = 8051,
    OP_INSERT_RUN_ATTRIBUTE_BATCH_MD_INSERT_RUN_ATTRIBUTE_BATCH_STUB = 8052,
    OP_INSERT_RUN_ATTRIBUTE_BATCH_SERIALIZE_MSG_FOR_CLIENT = 8053,
    OP_INSERT_RUN_ATTRIBUTE_BATCH_CREATE_MSG_FOR_CLIENT = 8054,
    OP_INSERT_RUN_ATTRIBUTE_BATCH_SEND_MSG_TO_CLIENT_OP_DONE = 8055,

//
    OP_INSERT_TIMESTEP_ATTRIBUTE_START = 8150,
    OP_INSERT_TIMESTEP_ATTRIBUTE_DEARCHIVE_MSG_FROM_CLIENT = 8151,
    OP_INSERT_TIMESTEP_ATTRIBUTE_MD_INSERT_TIMESTEP_ATTRIBUTE_STUB = 8152,
    OP_INSERT_TIMESTEP_ATTRIBUTE_SERIALIZE_MSG_FOR_CLIENT = 8153,
    OP_INSERT_TIMESTEP_ATTRIBUTE_CREATE_MSG_FOR_CLIENT = 8154,
    OP_INSERT_TIMESTEP_ATTRIBUTE_SEND_MSG_TO_CLIENT_OP_DONE = 8155,

//
    OP_INSERT_TIMESTEP_ATTRIBUTE_BATCH_START = 8250,
    OP_INSERT_TIMESTEP_ATTRIBUTE_BATCH_DEARCHIVE_MSG_FROM_CLIENT = 8251,
    OP_INSERT_TIMESTEP_ATTRIBUTE_BATCH_MD_INSERT_TIMESTEP_ATTRIBUTE_BATCH_STUB = 8252,
    OP_INSERT_TIMESTEP_ATTRIBUTE_BATCH_SERIALIZE_MSG_FOR_CLIENT = 8253,
    OP_INSERT_TIMESTEP_ATTRIBUTE_BATCH_CREATE_MSG_FOR_CLIENT = 8254,
    OP_INSERT_TIMESTEP_ATTRIBUTE_BATCH_SEND_MSG_TO_CLIENT_OP_DONE = 8255,

//
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_START = 8350,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_DEARCHIVE_MSG_FROM_CLIENT = 8351,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_MD_INSERT_VAR_ATTRIBUTE_BY_DIMS_STUB = 8352,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_SERIALIZE_MSG_FOR_CLIENT = 8353,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_CREATE_MSG_FOR_CLIENT = 8354,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_SEND_MSG_TO_CLIENT_OP_DONE = 8355,

//
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_START = 8450,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_DEARCHIVE_MSG_FROM_CLIENT = 8451,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_MD_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_STUB = 8452,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_SERIALIZE_MSG_FOR_CLIENT = 8453,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_CREATE_MSG_FOR_CLIENT = 8454,
    OP_INSERT_VAR_ATTRIBUTE_BY_DIMS_BATCH_SEND_MSG_TO_CLIENT_OP_DONE = 8455,

// //
//     OP_FULL_SHUTDOWN_START = 8550,
//     OP_FULL_SHUTDOWN_DONE = 8555,

};

#endif //SERVERTIMINGCONSTANTS_HH

