/*
 * Copyright 2018 National Technology & Engineering Solutions of
 * Sandia, LLC (NTESS). Under the terms of Contract DE-NA0003525 with NTESS,
 * the U.S. Government retains certain rights in this software.
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2018 Sandia Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#ifndef SERVERTIMINGCONSTANTS_HH
#define SERVERTIMINGCONSTANTS_HH

//unsigned short -> max value: 65535
enum SERVER_TIMING_CONSTANTS : unsigned short {

//10000 - errors
    ERR_ARGC = 10000,
    ERR_DIRMAN = 10001,
    ERR_DB_SETUP = 10002,

//md_server
    PROGRAM_START = 0,
    MPI_INIT_DONE = 1,
    REGISTER_OPS_DONE = 2,
    DB_SETUP_DONE = 3,
    DIRMAN_SETUP_DONE_INIT_DONE = 4,
    SHUTDOWN_START = 5,
    DB_ANALYSIS_DONE = 6,
    DB_CLOSED_SHUTDOWN_DONE = 7,

    DB_SIZES = 97,
    CLOCK_TIMES_NEW_PROC = 98,
    CLOCK_TIMES_DONE = 99,

//1000s - var ops, note: client side is from **00-**49
    OP_ACTIVATE_VAR_START = 1050,
    OP_ACTIVATE_VAR_DEARCHIVE_MSG_FROM_CLIENT = 1051,
    OP_ACTIVATE_VAR_MD_ACTIVATE_VAR_STUB = 1052,
    OP_ACTIVATE_VAR_SERIALIZE_MSG_FOR_CLIENT = 1053,
    OP_ACTIVATE_VAR_CREATE_MSG_FOR_CLIENT = 1054,
    OP_ACTIVATE_VAR_SEND_MSG_TO_CLIENT_OP_DONE = 1055,

    OP_CATALOG_VAR_START = 1150,
    OP_CATALOG_VAR_DEARCHIVE_MSG_FROM_CLIENT = 1151,
    OP_CATALOG_VAR_MD_CATALOG_VAR_STUB = 1152,
    OP_CATALOG_VAR_SERIALIZE_MSG_FOR_CLIENT = 1153,
    OP_CATALOG_VAR_CREATE_MSG_FOR_CLIENT = 1154,
    OP_CATALOG_VAR_SEND_MSG_TO_CLIENT_OP_DONE = 1155,

    OP_CREATE_VAR_START = 1250,
    OP_CREATE_VAR_DEARCHIVE_MSG_FROM_CLIENT = 1251,
    OP_CREATE_VAR_MD_CREATE_VAR_STUB = 1252,
    OP_CREATE_VAR_SERIALIZE_MSG_FOR_CLIENT = 1253,
    OP_CREATE_VAR_CREATE_MSG_FOR_CLIENT = 1254,
    OP_CREATE_VAR_SEND_MSG_TO_CLIENT_OP_DONE = 1255,

    OP_DELETE_VAR_START = 1350,
    OP_DELETE_VAR_DEARCHIVE_MSG_FROM_CLIENT = 1351,
    OP_DELETE_VAR_MD_DELETE_VAR_STUB = 1352,
    OP_DELETE_VAR_SERIALIZE_MSG_FOR_CLIENT = 1353,
    OP_DELETE_VAR_CREATE_MSG_FOR_CLIENT = 1354,
    OP_DELETE_VAR_SEND_MSG_TO_CLIENT_OP_DONE = 1355,

    OP_GET_CHUNK_LIST_START = 1450,
    OP_GET_CHUNK_LIST_DEARCHIVE_MSG_FROM_CLIENT = 1451,
    OP_GET_CHUNK_LIST_MD_GET_CHUNK_LIST_STUB = 1452,
    OP_GET_CHUNK_LIST_SERIALIZE_MSG_FOR_CLIENT = 1453,
    OP_GET_CHUNK_LIST_CREATE_MSG_FOR_CLIENT = 1454,
    OP_GET_CHUNK_LIST_SEND_MSG_TO_CLIENT_OP_DONE = 1455,

    OP_GET_CHUNK_START = 1550,
    OP_GET_CHUNK_DEARCHIVE_MSG_FROM_CLIENT = 1551,
    OP_GET_CHUNK_MD_GET_CHUNK_STUB = 1552,
    OP_GET_CHUNK_SERIALIZE_MSG_FOR_CLIENT = 1553,
    OP_GET_CHUNK_CREATE_MSG_FOR_CLIENT = 1554,
    OP_GET_CHUNK_SEND_MSG_TO_CLIENT_OP_DONE = 1555,

    OP_INSERT_CHUNK_START = 1650,
    OP_INSERT_CHUNK_DEARCHIVE_MSG_FROM_CLIENT = 1651,
    OP_INSERT_CHUNK_MD_INSERT_CHUNK_STUB = 1652,
    OP_INSERT_CHUNK_SERIALIZE_MSG_FOR_CLIENT = 1653,
    OP_INSERT_CHUNK_CREATE_MSG_FOR_CLIENT = 1654,
    OP_INSERT_CHUNK_SEND_MSG_TO_CLIENT_OP_DONE = 1655,

    OP_PROCESSING_VAR_START = 1750,
    OP_PROCESSING_VAR_DEARCHIVE_MSG_FROM_CLIENT = 1751,
    OP_PROCESSING_VAR_MD_PROCESSING_VAR_STUB = 1752,
    OP_PROCESSING_VAR_SERIALIZE_MSG_FOR_CLIENT = 1753,
    OP_PROCESSING_VAR_CREATE_MSG_FOR_CLIENT = 1754,
    OP_PROCESSING_VAR_SEND_MSG_TO_CLIENT_OP_DONE = 1755,

//2000s - var ops note: client side is from **00-**49
    OP_ACTIVATE_TYPE_START = 2050,
    OP_ACTIVATE_TYPE_DEARCHIVE_MSG_FROM_CLIENT = 2051,
    OP_ACTIVATE_TYPE_MD_ACTIVATE_TYPE_STUB = 2052,
    OP_ACTIVATE_TYPE_SERIALIZE_MSG_FOR_CLIENT = 2053,
    OP_ACTIVATE_TYPE_CREATE_MSG_FOR_CLIENT = 2054,
    OP_ACTIVATE_TYPE_SEND_MSG_TO_CLIENT_OP_DONE = 2055,

    OP_CATALOG_TYPE_START = 2150,
    OP_CATALOG_TYPE_DEARCHIVE_MSG_FROM_CLIENT = 2151,
    OP_CATALOG_TYPE_MD_CATALOG_TYPE_STUB = 2152,
    OP_CATALOG_TYPE_SERIALIZE_MSG_FOR_CLIENT = 2153,
    OP_CATALOG_TYPE_CREATE_MSG_FOR_CLIENT = 2154,
    OP_CATALOG_TYPE_SEND_MSG_TO_CLIENT_OP_DONE = 2155,

    OP_CREATE_TYPE_START = 2250,
    OP_CREATE_TYPE_DEARCHIVE_MSG_FROM_CLIENT = 2251,
    OP_CREATE_TYPE_MD_CREATE_TYPE_STUB = 2252,
    OP_CREATE_TYPE_SERIALIZE_MSG_FOR_CLIENT = 2253,
    OP_CREATE_TYPE_CREATE_MSG_FOR_CLIENT = 2254,
    OP_CREATE_TYPE_SEND_MSG_TO_CLIENT_OP_DONE = 2255,

    OP_DELETE_TYPE_START = 2350,
    OP_DELETE_TYPE_DEARCHIVE_MSG_FROM_CLIENT = 2351,
    OP_DELETE_TYPE_MD_DELETE_TYPE_STUB = 2352,
    OP_DELETE_TYPE_SERIALIZE_MSG_FOR_CLIENT = 2353,
    OP_DELETE_TYPE_CREATE_MSG_FOR_CLIENT = 2354,
    OP_DELETE_TYPE_SEND_MSG_TO_CLIENT_OP_DONE = 2355,

    OP_GET_ATTR_LIST_START = 2450,
    OP_GET_ATTR_LIST_DEARCHIVE_MSG_FROM_CLIENT = 2451,
    OP_GET_ATTR_LIST_MD_GET_ATTR_LIST_STUB = 2452,
    OP_GET_ATTR_LIST_SERIALIZE_MSG_FOR_CLIENT = 2453,
    OP_GET_ATTR_LIST_CREATE_MSG_FOR_CLIENT = 2454,
    OP_GET_ATTR_LIST_SEND_MSG_TO_CLIENT_OP_DONE = 2455,

    OP_GET_ATTR_START = 2550,
    OP_GET_ATTR_DEARCHIVE_MSG_FROM_CLIENT = 2551,
    OP_GET_ATTR_MD_GET_ATTR_STUB = 2552,
    OP_GET_ATTR_SERIALIZE_MSG_FOR_CLIENT = 2553,
    OP_GET_ATTR_CREATE_MSG_FOR_CLIENT = 2554,
    OP_GET_ATTR_SEND_MSG_TO_CLIENT_OP_DONE = 2555,

    OP_INSERT_ATTR_START = 2650,
    OP_INSERT_ATTR_DEARCHIVE_MSG_FROM_CLIENT = 2651,
    OP_INSERT_ATTR_MD_INSERT_ATTR_STUB = 2652,
    OP_INSERT_ATTR_SERIALIZE_MSG_FOR_CLIENT = 2653,
    OP_INSERT_ATTR_CREATE_MSG_FOR_CLIENT = 2654,
    OP_INSERT_ATTR_SEND_MSG_TO_CLIENT_OP_DONE = 2655,

    OP_PROCESSING_TYPE_START = 2750,
    OP_PROCESSING_TYPE_DEARCHIVE_MSG_FROM_CLIENT = 2751,
    OP_PROCESSING_TYPE_MD_PROCESSING_TYPE_STUB = 2752,
    OP_PROCESSING_TYPE_SERIALIZE_MSG_FOR_CLIENT = 2753,
    OP_PROCESSING_TYPE_CREATE_MSG_FOR_CLIENT = 2754,
    OP_PROCESSING_TYPE_SEND_MSG_TO_CLIENT_OP_DONE = 2755,
};

#endif //SERVERTIMINGCONSTANTS_HH