/* 
 * Copyright 2018 National Technology & Engineering Solutions of
 * Sandia, LLC (NTESS). Under the terms of Contract DE-NA0003525 with NTESS,
 * the U.S. Government retains certain rights in this software.
 *
 * The MIT License (MIT)
 * 
 * Copyright (c) 2018 Sandia Corporation
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */



#ifndef CLIENTTIMINGCONSTANTSREADHDF5_HH
#define CLIENTTIMINGCONSTANTSREADHDF5_HH

//unsigned short -> max value: 65535
enum CLIENT_TIMING_CONSTANTS_READ : unsigned short {
    ERR_ARGC = 10000,

    PROGRAM_START = 0,
    MPI_INIT_DONE = 1,
    INIT_VARS_DONE = 2,
    READING_START = 3,
    FIND_VARS_DONE = 4,
    READING_PATTERNS_START = 5,
    READING_PATTERNS_DONE = 6,

    READING_TYPE_PATTERNS_DONE = 7,
    EXTRA_TESTING_START = 8,
    EXTRA_TESTING_DONE = 9,
    READING_DONE = 10,
    READ_PATTERN_1_START = 11,
    READ_PATTERN_1_START_READING_VAR_DATA = 12,
    READ_PATTERN_1_DONE_READING_VAR_DATA = 13,

    READ_PATTERN_1_DONE = 14,
    READ_PATTERN_2_START = 15,
    READ_PATTERN_2_START_READING_VAR_DATA = 16,
    READ_PATTERN_2_DONE_READING_VAR_DATA = 17,
    READ_PATTERN_2_DONE = 18,
    READ_PATTERN_2_TYPE_START = 19,
    READ_PATTERN_2_START_CATALOGING_VAR_ATTRS = 20,
    READ_PATTERN_2_DONE_CATALOGING_VAR_ATTRS = 21,

    READ_PATTERN_2_START_READING_VAR_ATTR_DATA = 22,
    READ_PATTERN_2_DONE_READING_VAR_ATTR_DATA = 23,
    READ_PATTERN_2_TYPE_DONE = 24,
    READ_PATTERN_3_START = 25,
    READ_PATTERN_3_START_READING_VAR_DATA = 26,
    READ_PATTERN_3_DONE_READING_VAR_DATA = 27,

    READ_PATTERN_3_DONE = 28,
    READ_PATTERN_3_TYPE_START = 29,
    READ_PATTERN_3_START_CATALOGING_VAR_ATTRS = 30,
    READ_PATTERN_3_DONE_CATALOGING_VAR_ATTRS = 31,
    READ_PATTERN_3_START_READING_VAR_ATTR_DATA = 32,
    READ_PATTERN_3_DONE_READING_VAR_ATTR_DATA = 33,

    READ_PATTERN_3_TYPE_DONE = 34,
    READ_PATTERN_4_START = 35,
    READ_PATTERN_4_START_READING_VAR_DATA = 36,
    READ_PATTERN_4_DONE_READING_VAR_DATA = 37,
    READ_PATTERN_4_DONE = 38,
    READ_PATTERN_5_START = 39,
    READ_PATTERN_5_START_READING_VAR_DATA = 40,
    READ_PATTERN_5_DONE_READING_VAR_DATA = 41,

    READ_PATTERN_5_DONE = 42,
    READ_PATTERN_6_START = 43,
    READ_PATTERN_6_START_READING_VAR_DATA = 44,
    READ_PATTERN_6_DONE_READING_VAR_DATA = 45,
    READ_PATTERN_6_DONE = 46,
    BCAST_ENTRIES_COLLECTIVE_START = 47,
    BCAST_ENTRIES_COLLECTIVE_DONE = 48,

    READ_DATA_FOR_ATTRS_START = 49,
    READ_DATA_FOR_ATTRS_DONE = 50,
    READ_DATA_FOR_ATTR_START = 51,
    READ_DATA_FOR_ATTR_DONE = 52,

    CATALOG_ALL_RUN_ATTRIBUTES_COLLECTIVE_START = 53,
    CATALOG_ALL_RUN_ATTRIBUTES_COLLECTIVE_DONE = 54,

    CATALOG_TIMESTEP_COLLECTIVE_START = 55,
    CATALOG_TIMESTEP_COLLECTIVE_DONE = 56,
    CATALOG_ALL_TIMESTEP_ATTRIBUTES_COLLECTIVE_START = 57,
    CATALOG_ALL_TIMESTEP_ATTRIBUTES_COLLECTIVE_DONE = 58,
    CATALOG_VAR_COLLECTIVE_START = 59,
    CATALOG_VAR_COLLECTIVE_DONE = 60,

    CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_COLLECTIVE_START = 61,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_COLLECTIVE_DONE = 62,
    CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_COLLECTIVE_START = 63,
    CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_IN_TIMESTEP_COLLECTIVE_DONE = 64,
    CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_COLLECTIVE_START = 65,
    CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_IN_TIMESTEP_COLLECTIVE_DONE = 66,

    CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_COLLECTIVE_START = 67,
    CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_DIMS_IN_TIMESTEP_COLLECTIVE_DONE = 68,
    CATALOG_ALL_TIMESTEPS_WITH_VAR_COLLECTIVE_START = 69,
    CATALOG_ALL_TIMESTEPS_WITH_VAR_COLLECTIVE_DONE = 70,
    CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_COLLECTIVE_START = 71,
    CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_COLLECTIVE_DONE = 72,

    CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_COLLECTIVE_START = 73,
    CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_COLLECTIVE_DONE = 74,
    CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_COLLECTIVE_START = 75,
    CATALOG_ALL_RUN_ATTRIBUTES_WITH_TYPE_COLLECTIVE_DONE = 76,
    CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_COLLECTIVE_START = 77,
    CATALOG_ALL_TIMESTEP_ATTRIBUTES_WITH_TYPE_COLLECTIVE_DONE = 78,

    CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_COLLECTIVE_START = 79,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_DIMS_COLLECTIVE_DONE = 80,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_COLLECTIVE_START = 81,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_DIMS_COLLECTIVE_DONE = 82,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_COLLECTIVE_START = 83,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_COLLECTIVE_DONE = 84,

    CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_COLLECTIVE_START = 85,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_DIMS_COLLECTIVE_DONE = 86,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_COLLECTIVE_START = 87,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_COLLECTIVE_DONE = 88,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_COLLECTIVE_START = 89,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_DIMS_COLLECTIVE_DONE = 90,

    CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_COLLECTIVE_START = 91,
    CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_IN_TIMESTEP_COLLECTIVE_DONE = 92,
    CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_COLLECTIVE_START = 93,
    CATALOG_ALL_TYPES_WITH_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_IN_TIMESTEP_COLLECTIVE_DONE = 94,
    CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_COLLECTIVE_START = 95,
    CATALOG_ALL_TIMESTEPS_WITH_VAR_SUBSTR_COLLECTIVE_DONE = 96,

    CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_COLLECTIVE_START = 97,
    CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_COLLECTIVE_DONE = 98,
    CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_COLLECTIVE_START = 99,
    CATALOG_ALL_TIMESTEPS_WITH_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_COLLECTIVE_DONE = 100,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_COLLECTIVE_START = 101,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_COLLECTIVE_DONE = 102,

    CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_COLLECTIVE_START = 103,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_VAR_SUBSTR_DIMS_COLLECTIVE_DONE = 104,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_COLLECTIVE_START = 105,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_COLLECTIVE_DONE = 106,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_COLLECTIVE_START = 107,
    CATALOG_ALL_VAR_ATTRIBUTES_WITH_TYPE_VAR_SUBSTR_DIMS_COLLECTIVE_DONE = 108,



};

#endif 

